### PR TITLE
Fix pytube #1085 #1199

### PR DESCRIPTION
**Pull request by JavDomGom**
Test:
```python
from pytube import YouTube

yt = YouTube('https://www.youtube.com/watch?v=BGTRqGeIxOA')
captions = yt.captions.get('a.en')

print(captions.generate_srt_captions())
```
Output:
```
1
00:00:00,030 --> 00:00:04,020
the generation that's using the drugs

2
00:00:01,620 --> 00:00:06,930
now I would say is you can just forget

3
00:00:04,020 --> 00:00:08,760
it but I think there's a lot of hope and

4
00:00:06,930 --> 00:00:11,460
the ones who are in their preteens and

5
00:00:08,760 --> 00:00:12,780
the very young teens now because they
...
```

### CODE REVIEW

**Comment by arturtamborski** [comment]
thanks! this PR might need one more fix, see https://github.com/pytube/pytube/issues/1199#issuecomment-1016947797 for details

**Comment by glubsy** [comment]
Better do two separate pull requests for the two separate issues.

**Comment by RONNCC** [comment]
hey

thanks for the PR!

Can you add
- a unit test to show the behavior before and after
- some context on the need for the change 


Ideally this would 'break' in the future when youtube also changes behavior again and we can show it as a regression

**Comment by vladoossss** [comment]
> Test:
> 
> ```python
> from pytube import YouTube
> 
> yt = YouTube('https://www.youtube.com/watch?v=BGTRqGeIxOA')
> captions = yt.captions.get('a.en')
> 
> print(captions.generate_srt_captions())
> ```
> 
> Output:
> 
> ```
> 1
> 00:00:00,030 --> 00:00:04,020
> the generation that's using the drugs
> 
> 2
> 00:00:01,620 --> 00:00:06,930
> now I would say is you can just forget
> 
> 3
> 00:00:04,020 --> 00:00:08,760
> it but I think there's a lot of hope and
> 
> 4
> 00:00:06,930 --> 00:00:11,460
> the ones who are in their preteens and
> 
> 5
> 00:00:08,760 --> 00:00:12,780
> the very young teens now because they
> ...
> ```

Your timings are wrong(

**Comment by RONNCC** [comment]
presuming fixed?

**Pull request closed without merging**
