### PR TITLE
Improvement/docs

### LINKED ISSUE #874: Add documentation for registering on_progess and on_complete callbacks
The current documentation for registering on_progress and on_complete callbacks is incorrect, I believe due to changes from the pytube3->pytube merge. We've had a couple of people ask about how to use this, because the README says one thing, but in reality, this doesn't work correctly. This also isn't documented in readthedocs, so it should be added there as well.

See [this comment](https://github.com/nficano/pytube/issues/862#issuecomment-740014886) for a description of how to implement on_progress and on_complete callbacks.

### PR DESCRIPTION
**Pull request by tfdahlin**
Lot of doc changes here. Notably, removed a lot of the fluff from the README in favor of putting it into actual doc files for readthedocs, with a link pointing to that documentation. Also moved bumpversion and twine from the package requirements to the dev-package requirements so pytube remains dependency-free.

cc: @RONNCC

### CODE REVIEW

**Comment by tfdahlin** [comment]
@RONNCC @nficano either of you have a moment to provide some input on this? Don't merge this yet, just want your thoughts on extracting the detailed usage information from the README into readthedocs, and linking to that instead, so we have less of a wall of text there.

**Comment by tfdahlin** [comment]
https://github.com/tfdahlin/pytube/tree/improvement/docs you can check out what the README will look like after these changes over here

**Comment by RONNCC** [comment]
lgtm - would love if we could call out the documentation link more somehow 🤔  but not sure how hmm

**Comment by tfdahlin** [comment]
The link already exists in the about section on the side of the GitHub page, but we *could* move it up to the very beginning section of the README so it's not linked at the bottom if you think that would look better

**Comment by tfdahlin** [comment]
Updated the README, hopefully it makes the documentation link a little more visible.

**Comment by tfdahlin** [comment]
Gonna go ahead and merge this. We can update it later as needed

**Comment by RONNCC** [comment]
sgtm

**Pull request merged**
