### PR TITLE
Fix regex to find throttle function name

### LINKED ISSUE #1218: [BUG] 'NoneType' object has no attribute 'span'
**Before creating an issue**

Please confirm that you are on the latest version of pytube by installing from the source.
You can do this by running `python -m pip install git+https://github.com/pytube/pytube`.
Sometimes, the pypi library repository is not up to date, and your issue may have been fixed already!

**Describe the bug**
I have been running PyTube at different points today with success and fast downloads, but as of about 30 minutes ago I started to get this when I would run it:

`'NoneType' object has no attribute 'span'`

**To Reproduce**
I have tried on these two links, both of which were working earlier today:
-https://www.youtube.com/watch?v=twtGL8WbllM&ab_channel=HarritonRams
-https://www.youtube.com/watch?v=mA_3LkF_Cdo&ab_channel=IndianaSRN

Here is the code sample where it is being used:

`def download_youtube_video(row, game_id):
    filename = game_id + ".mp4"
    try:
        YouTube(row[0]).streams.filter(progressive=True, file_extension='mp4').order_by('resolution').desc().first().download(filename=filename)
        upload_successful = True
    except Exception as e: 
        print(e)
        print("HEY, LOOK HERE")
        print("I'VE GOT SOME BAD NEWS, SADLY")
        print("YOU'RE GOING TO HAVE TO DOWNLOAD AND UPLOAD THIS ONE MANUALLY")
        print(row[0])
        print(game_id)
        print("I TRIED TWO DIFFERENT YOUTUBE DOWNLOADER PACKAGES, BLAME THOSE F**** OVER AT GOOGLE FOR THIS")`

**Expected behavior**
I expected the video to be downloaded in the same directory as my python script as it was earlier today.

**Output**
`Traceback (most recent call last):
  File "test.py", line 3, in <module>
    YouTube("https://www.youtube.com/watch?v=mA_3LkF_Cdo&ab_channel=IndianaSRN").streams.filter(progressive=True, file_extension='mp4').order_by('resolution').desc().first().download(filename="hello.mp4")
  File "/Users/hunterhawley/Library/Python/3.7/lib/python/site-packages/pytube/__main__.py", line 292, in streams
    return StreamQuery(self.fmt_streams)
  File "/Users/hunterhawley/Library/Python/3.7/lib/python/site-packages/pytube/__main__.py", line 177, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "/Users/hunterhawley/Library/Python/3.7/lib/python/site-packages/pytube/extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "/Users/hunterhawley/Library/Python/3.7/lib/python/site-packages/pytube/cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "/Users/hunterhawley/Library/Python/3.7/lib/python/site-packages/pytube/cipher.py", line 387, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "/Users/hunterhawley/Library/Python/3.7/lib/python/site-packages/pytube/cipher.py", line 301, in get_throttling_function_code
    code_lines_list = find_object_from_startpoint(js, match.span()[1]).split('\n')
AttributeError: 'NoneType' object has no attribute 'span'`

**System information**
Please provide the following information:
- Python version: Python 3.7.1rc1
- Pytube version: Unsure as the provided way to find this didn't work
- Command used to install pytube: First was `python -m pip install pytube` but before posting it was `python -m pip install git+https://github.com/pytube/pytube`

### PR DESCRIPTION
**Pull request by glubsy**
The javascript now stores the throttling function name in an array.
cf. fix from yt-dlp at https://github.com/yt-dlp/yt-dlp/commit/48416bc4a8f1d5ff07d5977659cb8ece7640dcd8
Fix https://github.com/pytube/pytube/issues/1218

Context: the throttling function's name used to be a simple variable name, but now it is part of an array of symbols.
The javascript code used to look like this:
```javascript
a.C&&(b=a.get("n"))&&(b=Dea(b),a.set("n",b))}};
```
In the above case, `Dea` is the relevant function name.
Now the javascript code looks like this (white spaces added for clarity):
```javascript
var Bpa = [iha];
a.C && (b = a.get("n")) && (b = Bpa[0](b), a.set("n", b), Bpa.length || iha("")) }};
```
In the above case, `iha` is the relevant function name.
We try to capture the name of the array, as well as the index accessed from this array which should give the function name we are looking for.
If we only have one captured group, it means this is not an array (anymore) and the first capture group is the function name.
If we have 2 captured groups, we assume the first group is an array, and the second group is the index from which the target function name is accessed.

### CODE REVIEW

**Comment by juanchosaravia** [comment]
This is not working for me. Error:

```
File "...python3.9/http/client.py", line 614, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(1666671 bytes read, 7770513 more expected)
```

Video: https://www.youtube.com/watch?v=8bAzi4zIqK0

**Comment by glubsy** [comment]
@juanchosaravia this has nothing to do with this code.

**Comment by juanchosaravia** [comment]
I applied your changes locally and it was failing with this video. Does it works for you with that one? @glubsy

**Comment by RONNCC** [comment]
hey @glubsy 

thanks for the PR!

Can you add
- a unit test to show the behavior before and after
- some context on the need for the change 


Ideally this would 'break' in the future when youtube also changes behavior again and we can show it as a regression

**Comment by lucaArchidiacono** [comment]
> I applied your changes locally and it was failing with this video. Does it works for you with that one? @glubsy

I applied it locally on my side and it worked.

**Comment by glubsy** [comment]
@RONNCC added tests and some explanations.

**Comment by rabbitsf** [comment]
I also confirm it's working for me after applying the cipher.py here to my end.

**Comment by RONNCC** [comment]
@glubsy  Thanks for the work here -- LGTM :-)

**Review by pengyunshan — COMMENTED** [review]
thx for your fix

**Comment by ahmadadam12** [comment]
Good day,

I tried cipher.py here but it doesn't work for me. 

image

**Pull request merged**
