### PR TITLE
Fix empty channel videos

### PR DESCRIPTION
**Pull request by pishiko**
Fixed a bug that caused the channel's video list to be empty.

Support for Youtube html changes
Issue:https://github.com/pytube/pytube/issues/1408

### CODE REVIEW

**Review by mansoorahmd — APPROVED** [review]

**Comment by parvez-cet21** [comment]
When it will be merged?

**Comment by yeyu2** [comment]
Previously the Channel() function can retrieve all the videos including Shorts, the fix here can only read out the videos. The problem maybe is that youtube.com separated the shorts out of the videos tabs as an independent tab SHORTS recently.

**Review by palford7 — APPROVED** [review]

**Comment by thedtvn** [comment]
not work :\\\
image

**Comment by alebychac** [comment]
always get all the videos from the channel?

**Comment by RONNCC** [comment]
believe this should be fixed in recent changes? Please reopen PR if that's not the case :-)

**Comment by BuildWithData** [comment]
@RONNCC this has not been merged, if you check on master branch, last commit that changed the channel.py file is be07012c20162cfc44193514ba96931ab469b7aa on June 2021...

**Comment by thedtvn** [comment]
> @RONNCC this has not been merged, if you check on master branch, last commit that changed the channel.py file is be07012c20162cfc44193514ba96931ab469b7aa on June 2021...

@BuildWithData yes is has been a long time pytube has no update and merger

**Comment by RONNCC** [comment]
Could you write test cases perhaps

**Comment by BuildWithData** [comment]
@RONNCC I'd love to do it myself, but I have not found any docs on how to run the test suite and/or its structure. I tried with pytest and got 1 failed tests and 78 errors... any helpful link on it ?

**Comment by RONNCC** [comment]
Hmm could you post the errors, bit surprised there

**Comment by BuildWithData** [comment]
> Hmm could you post the errors, bit surprised there

made a [short video](https://youtu.be/N0_ctnsKlmw) so you can check all the steps

**Comment by gregschwartz** [comment]
Still running into this issue, would love to see the fix merged in 😇

**Comment by ttrreevvoorr** [comment]
please reopen this PR, as many are saying it fixes their issues: https://github.com/pytube/pytube/issues/1627

**Comment by emresagir** [comment]
Problem still continues. This is a valid fix.

**Pull request closed without merging**
