### PR TITLE
Fix #609

### LINKED ISSUE #609: KeyError: 'formats' error on certain live feeds
Installation (Python 3.6.9, pytube3-9.6.4):

```bash
pip3 uninstall -y pytube3
pip3 install git+https://github.com/nficano/pytube
python3
```

Test:

```python
from pytube import YouTube
YouTube('https://www.youtube.com/watch?v=5YceQ8YqYMc')
```

Error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".local/lib/python3.6/site-packages/pytube/__main__.py", line 92, in __init__
    self.descramble()
  File ".local/lib/python3.6/site-packages/pytube/__main__.py", line 132, in descramble
    apply_descrambler(self.player_config_args, fmt)
  File ".local/lib/python3.6/site-packages/pytube/extract.py", line 281, in apply_descrambler
    formats = json.loads(stream_data["player_response"])["streamingData"]["formats"]
KeyError: 'formats'
```

Ref. https://github.com/get-pytube/pytube3/issues/74 (maybe wrong place there, will remove that note if the issue is answered here)

### PR DESCRIPTION
**Pull request by tooxo**
This fixes a KeyError ocurring on livestreams.

### CODE REVIEW

**Comment by Ircama** [comment]
Thanks for this PR.

While testing it, I get *pytube.exceptions.RegexMatchError: get_ytplayer_config: could not find match for config_patterns*.

Steps to reproduce the error:

```python
pip3 uninstall -y pytube3
pip3 install "git+https://github.com/tooxo/pytube.git@fix_609"
python3
from pytube import YouTube
YouTube('https://www.youtube.com/watch?v=5YceQ8YqYMc')
```

Error output:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".local/lib/python3.6/site-packages/pytube/__main__.py", line 91, in __init__
    self.prefetch()
  File ".local/lib/python3.6/site-packages/pytube/__main__.py", line 183, in prefetch
    self.js_url = extract.js_url(self.watch_html)
  File ".local/lib/python3.6/site-packages/pytube/extract.py", line 143, in js_url
    base_js = get_ytplayer_config(html)["assets"]["js"]
  File ".local/lib/python3.6/site-packages/pytube/extract.py", line 202, in get_ytplayer_config
    raise RegexMatchError(caller="get_ytplayer_config", pattern="config_patterns")
pytube.exceptions.RegexMatchError: get_ytplayer_config: could not find match for config_patterns
```

**Comment by tooxo** [comment]
> Thanks for this PR.
> 
> While testing it, I get _pytube.exceptions.RegexMatchError: get_ytplayer_config: could not find match for config_patterns_.
> 
> Steps to reproduce the error:
> 
> ```python
> pip3 uninstall -y pytube3
> pip3 install "git+https://github.com/tooxo/pytube.git@fix_609"
> python3
> from pytube import YouTube
> YouTube('https://www.youtube.com/watch?v=5YceQ8YqYMc')
> ```
> 
> Error output:
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File ".local/lib/python3.6/site-packages/pytube/__main__.py", line 91, in __init__
>     self.prefetch()
>   File ".local/lib/python3.6/site-packages/pytube/__main__.py", line 183, in prefetch
>     self.js_url = extract.js_url(self.watch_html)
>   File ".local/lib/python3.6/site-packages/pytube/extract.py", line 143, in js_url
>     base_js = get_ytplayer_config(html)["assets"]["js"]
>   File ".local/lib/python3.6/site-packages/pytube/extract.py", line 202, in get_ytplayer_config
>     raise RegexMatchError(caller="get_ytplayer_config", pattern="config_patterns")
> pytube.exceptions.RegexMatchError: get_ytplayer_config: could not find match for config_patterns
> ```

This is unrelated to my PR, maybe open a new issue?

**Comment by Ircama** [comment]
> This is unrelated to my PR, maybe open a new issue?

Yes, right, thanks for your swift feedback.

Opened https://github.com/nficano/pytube/issues/614.

**Comment by Ircama** [comment]
I still cannot stream the live feed with your modifications, even if I get a list of URLs.

Take for instance:

```python
from pytube import YouTube
yt = YouTube('https://www.youtube.com/watch?v=29EFXG2WJL8')
for stream in yt.streams:
     print(stream.url)
```

which is a working live feed at the moment of writing.

None of the returned `videoplayback?` queries works.

I think you also need to allow returning the *hlsManifestUrl* (and *dashManifestUrl*) from `https://www.youtube.com/get_video_info?&video_id=29EFXG2WJL8` or similar.

For instance, I am able to play the live stream with URL in *urlHLS* string (m3u8 manifest) obtained from the following:

```python
import urllib.request
import re
videoId = "29EFXG2WJL8"
url = urllib.request.urlopen("https://www.youtube.com/get_video_info?&video_id=" + videoId)
videoinfo = urllib.parse.unquote_plus(url.read().decode())
hlsdata = videoinfo.replace('\\/','/').replace('\\"','"')
urlHLS = re.findall('hlsManifestUrl":"(http.*?\.m3u8)"(?:}|,)', hlsdata, re.S)[0]
urlDASH = re.findall('dashManifestUrl":"(http.*?)"(?:}|,)', hlsdata, re.S)[0]
title = re.findall('"title":"([^"]*)"', hlsdata, re.S)[0]
author = re.findall('"author":"([^"]*)"', hlsdata, re.S)[0]
shortDescription = re.findall('"shortDescription":"([^"]*)"', hlsdata, re.S)[0]
isLiveDefaultBroadcast = re.findall('"isLiveDefaultBroadcast":([^,}]*)[,}]', hlsdata, re.S)[0] == 'true'
isLowLatencyLiveStream = re.findall('"isLowLatencyLiveStream":([^,}]*)[,}]', hlsdata, re.S)[0] == 'true'
isLiveContent = re.findall('"isLiveContent":([^,}]*)[,}]', hlsdata, re.S)[0] == 'true'
startTimestamp = re.findall('"startTimestamp":"([^"]*)"', hlsdata, re.S)[0]
thumbnail = re.findall('thumbnails":.*"(http.*?)"(?:}|,)', hlsdata, re.S)[0]
```

**Comment by Ircama** [comment]
I finally noticed that the same can be obtained with the following (undocumented) *pytube* API:

```
yt.player_response
```

This returns a dictionary that is also searchable with the `get` method:

```python
from pytube import YouTube
yt = YouTube('https://www.youtube.com/watch?v=29EFXG2WJL8')

# get HLS manifest (which allows streaming the live HLS content)
yt.player_response.get("streamingData", {}).get("hlsManifestUrl")

# get DASH manifest
yt.player_response.get("streamingData", {}).get("dashManifestUrl")

# Other metadata:
yt.player_response.get("streamingData", {}).get("expiresInSeconds")

yt.player_response.get("videoDetails", {}).get("isLive")

yt.player_response.get("videoDetails", {}).get("shortDescription")

yt.player_response.get("videoDetails", {}).get("isLiveDefaultBroadcast")

yt.player_response.get("videoDetails", {}).get("isLowLatencyLiveStream")

yt.player_response.get("videoDetails", {}).get("isLiveContent")

yt.player_response.get("videoDetails", {}).get("author")

yt.player_response.get("microformat", {})

yt.player_response.get("microformat", {}).get("playerMicroformatRenderer").get("liveBroadcastDetails")

yt.player_response.get("microformat", {}).get("playerMicroformatRenderer").get("liveBroadcastDetails").get("startTimestamp")

yt.player_response.get("microformat", {}).get("playerMicroformatRenderer").get("ownerChannelName")

yt.player_response.get("microformat", {}).get('playerMicroformatRenderer').get('uploadDate')

yt.player_response.get("microformat", {}).get('playerMicroformatRenderer').get('publishDate')

```

Such API solves my problem.

**Comment by thpryrchn** [comment]
I recommend Pulling this commit! It fixes the problem of being able to parse the live stream that I was having problems with.
without it , it errors at the `yt = YouTube('https://www.youtube.com/watch?v=<videoId>')`

@Ircama  
Thank you so much for pointing out the `yt.player_response.get` method, as I am not wanting to download the youtube, but obtain the Metadata, like Descriptions, and manifest urls.

**Comment by tooxo** [comment]
Yea think so too, but this repo seems dead to me. Maybe they are searching for new maintainers?

**Comment by tooxo** [comment]
Yea think so too, but this repo seems dead to me. Maybe they are searching for new maintainers?

**Comment by thpryrchn** [comment]
Yea, 6 days ago, the readme had a call for a new maintainer, then 18 hours ago, it was removed, and replaced with an ad to sponsor the project. 
I had been using youtube-dl to make a info.json to parse everything I needed from a live channel, but one time when the channel wasn't live, it got in a playlist loop that caused my IP address to get banned, so it seems. 
I wrote a simple little python script to output json for the videoId. 
```python
#!/usr/bin/env python3

from pytube import YouTube
import json
import sys

yt = YouTube('https://www.youtube.com/watch?v=' + sys.argv[1])
test = {}
test['videoDetails'] = yt.player_response.get("videoDetails")
test['streamingData'] = yt.player_response.get("streamingData")
test['microformat'] = yt.player_response.get("microformat")
print(json.dumps(test, indent=2))
```
Then I use `jq` to parse the output for bash. Currently I pipe the output to a file, but I am going to change it to output the file itself, as when it fails, it still creates a 0 byte file.
```bash
vidtitle="$(jq -r .microformat.playerMicroformatRenderer.title.simpleText "${File%.*}".info.n.json)"
description="$(jq -r .microformat.playerMicroformatRenderer.title.simpleText "${File%.*}".info.n.json)"
hlsurl="$(jq -r .streamingData.hlsManifestUrl "${File%.*}".info.n.json)"
tags=$(jq  .videoDetails.keywords "${File%.*}".info.n.json | tr -d "\n" | sed -e 's/\[\ \ //g' -e 's/\"//g' -e 's/\]//g' -e 's/,  /,/g')
```
After all this, I put it on my server, and You-get also got the dreaded "Error 426, too many attempts". 

My workaround was to setup a socks5 server on another server of mine, and have the youtube-dl connect through that. If you-get had proxy support, I would rather use that. I think it doesn't use as many connections as youtube-dl does to get the information I need, and therefore won't get me lockedout. I am going to give it a few days and see if my ip address gets unblocked. If it doesn't I will have to setup a new server.. which would be a pain.

**Comment by tooxo** [comment]
I think I would be able to maintain this project, if the position is still free @nficano

**Comment by thpryrchn** [comment]
@tooxo Wow! Huge code update to pytube! I will have to try it now :)

**Comment by thpryrchn** [comment]
Just installed latest code, and it still fails on live streams...
```
$ pytube3 https://www.youtube.com/watch?v=9Auq9mYxFEE --list
Loading video...
Traceback (most recent call last):
  File "/usr/local/bin/pytube3", line 33, in <module>
    sys.exit(load_entry_point('pytube3==9.6.4', 'console_scripts', 'pytube3')())
  File "/usr/local/lib/python3.8/site-packages/pytube3-9.6.4-py3.8.egg/pytube/cli.py", line 52, in main
  File "/usr/local/lib/python3.8/site-packages/pytube3-9.6.4-py3.8.egg/pytube/__main__.py", line 103, in __init__
  File "/usr/local/lib/python3.8/site-packages/pytube3-9.6.4-py3.8.egg/pytube/__main__.py", line 147, in descramble
  File "/usr/local/lib/python3.8/site-packages/pytube3-9.6.4-py3.8.egg/pytube/extract.py", line 296, in apply_descrambler
KeyError: 'formats'
```
So @nficano, the code from this pull request is still needed.

**Comment by RONNCC** [comment]
@thpryrchn  @tooxo  Believe this should now be fixed.
Please re-open if issue still persists. 

Thanks!

**Comment by tooxo** [comment]
@RONNCC If you try this on the latest version the error still persists. https://github.com/nficano/pytube/pull/612#issuecomment-660591561

So, a reopen should be considered.

**Comment by RONNCC** [comment]
@tooxo  -- @tfdahlin  submitted a change to master which I just pulled this morning in #790  😄

**Pull request closed without merging**
