### PR TITLE
browse enable

### PR DESCRIPTION
**Pull request by rexwu1104**
The result of API call is like person do a click at the url. (maybe)

### CODE REVIEW

**Comment by rexwu1104** [comment]
this is used to my project, but my project just a crawler XD

**Comment by RONNCC** [comment]
hey @rexwu1104  -- can you add to the description; it's unclear the purpose of the change

**Comment by rexwu1104** [comment]
are you mean the result of the api call?
sorry, my english is so poor.

**Comment by RONNCC** [comment]
trying to get at what is the purpose of the change? :-)

**Comment by rexwu1104** [comment]
let the innertuble can call the browse function? I think.
but if it cannot help you, you can reject these.

**Pull request closed without merging**
