### PR TITLE
add base google custom search

### PR DESCRIPTION
**Pull request by Dinkins**

### CODE REVIEW

**Comment by Dinkins** [comment]
connects to #8

**Comment by logston** [comment]
@akrawchyk What does BEM mean?

**Comment by akrawchyk** [comment]
@logston *B*lock *E*lement *M*odifier is a methodology for writing and structure your stylesheets. It proposes a few rules to follow in order to limit specificity of your selectors, namespace styles in a predictable way, and promotes componetizing and reusing of your styles (I think I could word that better...)

Personally, I like to follow [SUITCSS naming conventions](https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md) since it is more clear to me and easier to read. Check out more at https://suitcss.github.io/.

Either way, I was just joking around with @Dinkins, we're coworkers 👷

**Comment by akrawchyk** [comment]
Forgot to link an article describing the approach at a high-level http://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/.

**Comment by logston** [comment]
ah! :) Thanks.

**Pull request merged**
