### PR TITLE
use pytube3 for python 3 (could close #672)

### LINKED ISSUE #672: ImportError: cannot import name 'quote' from 'pytube.compat'
Whenever I enter `pytube` into command prompt, I get the following error:

```
Traceback (most recent call last):
  File "c:\program files\python\installations\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python\installations\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\boob\AppData\Roaming\Python\Python38\Scripts\pytube.exe\__main__.py", line 4, in <module>
  File "C:\Users\boob\AppData\Roaming\Python\Python38\site-packages\pytube\__init__.py", line 16, in <module>
    from pytube.streams import Stream
  File "C:\Users\boob\AppData\Roaming\Python\Python38\site-packages\pytube\streams.py", line 17, in <module>
    from pytube import extract
  File "C:\Users\boob\AppData\Roaming\Python\Python38\site-packages\pytube\extract.py", line 7, in <module>
    from pytube.compat import quote
ImportError: cannot import name 'quote' from 'pytube.compat' (C:\Users\boob\AppData\Roaming\Python\Python38\site-packages\pytube\compat.py)
```

### PR DESCRIPTION
**Pull request by maphew**

### CODE REVIEW

**Comment by RONNCC** [comment]
@maphew i believe that is a different library entirely so I'm a bit unclear if it fixes the root issue or replaces pytube with a different library when loading

We likely need to update our requirements.txt -- would definitely appreciate assistance here!

**Comment by maphew** [comment]
@RONNCC Thanks for the prompt attention. I didn't realize pytube & pytube3 are in a state of flux, once forked and now trying to come back together. The PR was just a naive implementation of the comments in #672. I'll see if I can find a way to help. There's also the fork-of-fork https://github.com/H4KKR/pytubeX. 

A suggestion:  create an issue out of the "actively calling for maintainers" part of the Readme. Pin it. Then reach out to folks like @H4KKR who have been active fixing bugs and making PRs in recent months.

**Comment by maphew** [comment]
(and: I'll close this PR after you've read it. It doesn't serve the right purpose)

**Comment by RONNCC** [comment]
> @RONNCC Thanks for the prompt attention. I didn't realize pytube & pytube3 are in a state of flux, once forked and now trying to come back together. The PR was just a naive implementation of the comments in #672. I'll see if I can find a way to help. There's also the fork-of-fork https://github.com/H4KKR/pytubeX.

 I'm not really sure how they go together/work - need to dive into that more  😄 


> A suggestion: create an issue out of the "actively calling for maintainers" part of the Readme. Pin it. Then reach out to folks like @H4KKR who have been active fixing bugs and making PRs in recent months.
Good idea!  Done in #698

**Pull request closed without merging**
