### PR TITLE
Improvements to titles and cipher key

### PR DESCRIPTION
**Pull request by rsolanodev**
Some bugs that were affecting the use of the library have been fixed.

### CODE REVIEW

**Comment by RONNCC** [comment]
@rsolanoweb  (i'm not a committer) but can you rebase your changes

**Comment by RONNCC** [comment]
@rsolanoweb  -- are these updates still relevant? Would love to merge into the repo 

Thanks

**Comment by rsolanodev** [comment]
@RONNCC Hello friend, these updates aren't relevant since the bugs have been fixed in the master branch.

**Comment by RONNCC** [comment]
@rsolanoweb  ah thanks! -- would love your assistance /w any other bugs you might have found!

**Pull request closed without merging**
