### PR TITLE
Changed print statement to logging

### PR DESCRIPTION
**Pull request by joaoricardo000**
This fixes this issue: https://github.com/nficano/pytube/issues/61

### CODE REVIEW

**Comment by josegonzalez** [comment]
Thanks for the pr!

**Comment by josegonzalez** [comment]
I've released 0.3.0

**Comment by joaoricardo000** [comment]
Nice, already updated on my requirements!
Thanks for the lib!

**Comment by andreibastos** [comment]
parabéns

<div>-------- Mensagem original --------</div><div>De : João Ricardo notifications@github.com </div><div>Data:05/09/2015  23h19  (GMT-03:00) </div><div>Para: nficano/pytube pytube@noreply.github.com </div><div>Assunto: Re: [pytube] Changed print statement to logging (#62) </div><div>
</div>Nice, already updated on my requirements!
Thanks for the lib!

**Comment by josegonzalez** [comment]
de nada!

**Pull request merged**
