### PR TITLE
Fix player response and basejs extraction from html

### PR DESCRIPTION
**Pull request by tooxo**
This fixes issues like #731 as well as extraction of specific urls with a new template on youtubes side. 

This is for now the only url I could find, which needs the url fix. 
https://www.youtube.com/watch?v=gAs9HZC9c7Y

### CODE REVIEW

**Comment by jwbn** [comment]
Works well for me, thanks. Tried it on another video that had the same issue as [this](https://www.youtube.com/watch?v=gAs9HZC9c7Y) and it worked.

**Comment by ocervell** [comment]
Works !

**Comment by RONNCC** [comment]
@tooxo  is this still needed? seems like most recent  version fixes already

**Comment by tooxo** [comment]
> @tooxo is this still needed? seems like most recent version fixes already

Yea the changes were committed here: https://github.com/a-czyrny/pytube/commit/1113b957543cbb07195b3e150f1217088fa084a1

**Comment by RONNCC** [comment]
Thanks @tooxo !

**Pull request closed without merging**
