### PR TITLE
Fix #1181: Verify Stream attribute before use it.

### LINKED ISSUE #1181: 'Stream' object has no attribute 'fps'
pytube 11.0.2, python 3.10.1

Trying to filter YouTube streams by fps and got  Error.

Input: YouTube("https://www.youtube.com/watch?v=xIANCyXGN5I").streams.filter(fps=30)
Ouput: AttributeError: 'Stream' object has no attribute 'fps'

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Main\Desktop\youtubeDL\lib\site-packages\pytube\query.py", line 175, in filter
    return self._filter(filters)
  File "C:\Users\Main\Desktop\youtubeDL\lib\site-packages\pytube\query.py", line 181, in _filter
    return StreamQuery(list(fmt_streams))
  File "C:\Users\Main\Desktop\youtubeDL\lib\site-packages\pytube\query.py", line 129, in <lambda>
    filters.append(lambda s: s.fps == fps)
AttributeError: 'Stream' object has no attribute 'fps'

### PR DESCRIPTION
**Pull request by gaetan1903**
before run filter condition, verify if the attribute exists,

### CODE REVIEW

**Comment by gaetan1903** [comment]
image

**Comment by gaetan1903** [comment]
image
There is a object doesn't have a fps attribut

**Comment by gaetan1903** [comment]
@glubsy can you check and close this if is bad idea or not compliant?

**Review by glubsy — APPROVED** [review]
A few remarks:

* Paste text instead of screenshots. It makes it easier to grab the video ID for others to test, for example:
```python
from pytube import YouTube

yt = YouTube("https://www.youtube.com/watch?v=xIANCyXGN5I")

for k,v in enumerate(yt.streams):
    try:
        print(f"{k}, fps: {v.fps}")    
    except Exception as e:
        print(e)
        print(f"{k}, {v}")

for stream in yt.streams.filter(fps=30):
    print(f"filtered: {stream}")
    assert hasattr(stream, "fps")
```
* It might be a good idea to add some tests in test_query.py

Other than that, after testing a bit, it looks good to me. Good patch!

**Pull request closed without merging**
