### PR TITLE
Fixed all the Recent Error

### PR DESCRIPTION
**Pull request by dudegladiator**
Updated Innertube.py and request.py

### CODE REVIEW

**Comment by dudegladiator** [comment]
pip install git+https://github.com/dudegladiator/pytube.git
Works Perfectly
Try - https://youtubedownloader.streamlit.app/
Follow

**Comment by boardkeystown** [comment]
> pip install git+https://github.com/dudegladiator/pytube.git Works Perfectly

bruh you rock!!!!!! 

Can you please explain what you fixed in it?

I'm just curious what broke in the first place. TBH don't understand the code base that much but trying to learn. Last time it broke this bad it was a simple regex issue. I just cloned pytube and changed the line and used that for ages until it broke. Then I just reinstalled the pytube and it worked again. 

So for the time being I'll be using your fork but just want to know what youtube changed this time.

**Comment by Da-ladder** [comment]
@boardkeystown looks like he updated the Android version which is why the video installer was not installing videos. I was trying to get it to work with web but the download was throttled (presumably by a low HTTP chunk size which I could not figure out how to change without breaking the entire lib). He seems to also have added other clients like IOS. @dudegladiator tysm for fixing the library. Can you tell us how you updated the android version so this issue can be easily fixed later on? Thanks!

**Comment by Nyrok** [comment]
Tested and approved.

**Comment by sam31046** [comment]
Thanks, bro! You're a legend!
I am curious about the API keys, It only uses the same one. Is this an issue? What's your opinion about implementing a random function on API key list?

**Comment by DominikSLK** [comment]
Thanks!

**Comment by RONNCC** [comment]
believe recent patches should fix existing errors.

**Pull request closed without merging**
