### PR TITLE
Playlist download support

### PR DESCRIPTION
**Pull request by ahmedsadman**
Added support for downloading whole playlist of youtube channel.

### CODE REVIEW

**Comment by DonoA** [comment]
I would recommend trying to remove any dependencies. One of the great features of pytube is that it requires no dependencies to use.

**Comment by ahmedsadman** [comment]
Okay, then I have to make good amount of changes in the code. I am working on it. Thanks for the help @DonoA

**Comment by ahmedsadman** [comment]
@DonoA Okay, looks like I needed to add unit-test to make coveralls successful, not any dependency. Although I have removed all the dependencies

@nficano This build has successfully passed all tests, hope that you will have a look into it.

**Review by nficano — APPROVED** [review]

**Comment by nficano** [comment]
This PR made my day

**Pull request merged**
