### PR TITLE
Update regex

### LINKED ISSUE #354: RegexMatchError encodeURIComponent
Hello everyone.

I made this Python3 program and it was working fine but I recently got this error. 

```
  File "downloader.py", line 21, in <module>
    yt = YouTube(video)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/__main__.py", line 88, in __init__
    self.prefetch_init()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/__main__.py", line 97, in prefetch_init
    self.init()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/__main__.py", line 133, in init
    mixins.apply_signature(self.player_config_args, fmt, self.js)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/mixins.py", line 49, in apply_signature
    signature = cipher.get_signature(js, stream['s'])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/cipher.py", line 250, in get_signature
    tplan = get_transform_plan(js)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/cipher.py", line 72, in get_transform_plan
    return regex_search(pattern, js, group=1).split(';')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/helpers.py", line 65, in regex_search
    .format(pattern=pattern),
pytube.exceptions.RegexMatchError: regex pattern (encodeURIComponent=function\(\w\){[a-z=\.\(\"\)]*;(.*);(?:.+)}) had zero matches
```

I have modified cipher.py and helpers.py files without any result.

### PR DESCRIPTION
**Pull request by grking8**
- fixes https://github.com/nficano/pytube/issues/354 as per https://github.com/rg3/youtube-dl/commit/fa4ac365f69cbd51e4c9801984ebea49a12825b7 and https://github.com/rg3/youtube-dl/issues/18921

### CODE REVIEW

**Comment by eateshk** [comment]
Thanks for the PR @grking8, I recently used this to fix this issue with the library locally. Maintainers, request you to kindly merge it.

**Comment by aliakseis** [comment]
Thanks! It looks like the fix needed.

**Comment by FreakyForester** [comment]
I have changed my get_initital_function_name, however, I am still getting the same error specified above:

  File "C:\Users\justi\Anaconda3\envs\youtubemp3\lib\site-packages\pytube\helpers.py", line 65, in regex_search
    .format(pattern=pattern),
pytube.exceptions.RegexMatchError: regex pattern (encodeURIComponent=function\(\w\){[a-z=\.\(\"\)]*;(.*);(?:.+)}) had zero matches

any help on this?

**Comment by grking8** [comment]
@FreakyForester can you give an example url of a video you are trying to download please?

**Comment by FreakyForester** [comment]
I believe this was the URL:

https://www.youtube.com/watch?v=SEz0-fdi-5c

**Comment by grking8** [comment]
Thanks. I was able to download this url ok

I see you are using a conda environment. Would it be possible to check when you run your script in the conda env, it is using the amended version of `get_initial_function_name`? For example, by adding at the start of `get_initial_function_name`
```
    print('*' * 50)
    print('*' * 50)
    print('*' * 50)
    print('*' * 50)
    print('*' * 50)
    print('*' * 50)
```

**Comment by FreakyForester** [comment]
Hmm... Oddly, today when I opened the project, I cannot import YouTube from pytube...


Getting error: ImportError: cannot import name 'Youtube'

However, I can see the pytube module listed under my External Libraries -> site-packages.

If I could get this resolved, I'd be able to test if the function is being hit, however, I remember the get_initial_function_name function being called when I was debugging.

**Comment by FreakyForester** [comment]
Awesome, it's working.

Ultimately, I am trying to convert the mp4 to a mp3. Is there any way I can save the mp3 file as a variable to pass into another converter function without downloading the mp4 first?

**Pull request merged**
