### PR TITLE
Update extract.py

### PR DESCRIPTION
**Pull request by Mayur333221**
One line 301. cipher key is no longer existed in formats.  Its turned to signatureCipher. So a minute edit

### CODE REVIEW

**Comment by xXSlothaiXx** [comment]
Thank you, you are a life saver, hope this gets updated soon.

**Comment by shaysingh818** [comment]
Worked for me!! Very Quick fix, Thank you!

**Comment by Mayur333221** [comment]
Welcome😍😄❤

**Comment by BunnyBrewery** [comment]
This still doesn't work for me. I changed the file. Still the same error.

**Comment by antnieszka** [comment]
Works for me too, thanks for the patch! 😄

**Comment by to7m** [comment]
Would it be appropriate to replace
`parse_qs(formats[i]["signatureCipher"]) for i, data in enumerate(formats)`
with
`parse_qs(data["signatureCipher"]) for data in formats`
? I'm thinking there might be a consistency-based reason for the former?

**Comment by antnieszka** [comment]
> 
> 
> Would it be appropriate to replace
> `parse_qs(formats[i]["signatureCipher"]) for i, data in enumerate(formats)`
> with
> `parse_qs(data["signatureCipher"]) for data in formats`
> ? I'm thinking there might be a consistency-based reason for the former?

Yep, looks cleaner and a bit more pythonic to me 😉

**Comment by shaysingh818** [comment]
Is anyone in contact with the owner of this PIP lib? My project kinda depends on it and if we could push the cipher FIX to the master branch, that would be very helpful.

**Comment by to7m** [comment]
https://github.com/nficano/pytube/blob/master/README.md

As much as I'd like to take over, the entirety of my life code contribution experience is that in my comment above...

**Comment by antnieszka** [comment]
well, that's the downside of open software not backed by any companies/organizations :/ @to7m did you volunteer?

**Comment by to7m** [comment]
I didn't. I guess I will if no-one else does, but as I've never handled a pull request in my life, I'm hoping someone else has...

This patch shows that it should be community-maintainable to some extent without active development at least!

**Comment by wimpykid719** [comment]
it worked for me thank you so much!!

**Comment by RONNCC** [comment]
Issue seems to be fixed already -- please re-open if this isn't the case :)

**Pull request closed without merging**
