### PR TITLE
Critical Bugfix - Extraction of function not working

### PR DESCRIPTION
**Pull request by belthaZornv**
https://github.com/nficano/pytube/issues/695

### CODE REVIEW

**Comment by 7a35090f** [comment]
Works a charm!

**Comment by spongezhang** [comment]
Confirmed to work. Thanks a lot!

**Comment by belthaZornv** [comment]
> Confirmed to work. Thanks a lot!

You're welcome dude!

**Comment by l0ophole** [comment]
I'm still getting the same error after installing this pull request.

`KeyError: 'formats'`

I installed it using this command. Is this correct?

`sudo python3 -m pip install "git+https://github.com/belthaZornv/pytube@773866382c3412e01f97f242e753cf32f52aaefa"`

**Comment by 512DuncanL** [comment]
how to install this pull request?

**Comment by light42** [comment]
@512DuncanL @l0ophole 

pip install git+https://github.com/nficano/pytube.git@refs/pull/701/head

**Comment by l0ophole** [comment]
@light42 

```
[arch2 ~]$ sudo python3 -m pip install "git+https://github.com/nficano/pytube.git@refs/pull/701/head"
Collecting git+https://github.com/nficano/pytube.git@refs/pull/701/head
  Cloning https://github.com/nficano/pytube.git (to revision refs/pull/701/head) to /tmp/pip-req-build-5gusbcfq
  Running command git clone -q https://github.com/nficano/pytube.git /tmp/pip-req-build-5gusbcfq
  WARNING: Did not find branch or tag 'refs/pull/701/head', assuming revision or ref.
  Running command git fetch -q https://github.com/nficano/pytube.git refs/pull/701/head
  Running command git checkout -q 773866382c3412e01f97f242e753cf32f52aaefa
Requirement already satisfied (use --upgrade to upgrade): pytube3==9.6.4 from git+https://github.com/nficano/pytube.git@refs/pull/701/head in /usr/lib/python3.8/site-packages
Requirement already satisfied: typing_extensions in /usr/lib/python3.8/site-packages (from pytube3==9.6.4) (3.7.4.2)
Building wheels for collected packages: pytube3
  Building wheel for pytube3 (setup.py) ... done
  Created wheel for pytube3: filename=pytube3-9.6.4-py3-none-any.whl size=38870 sha256=e0d8fcb966fe359c8d91288c029a3cb016473ee0f9b5a44f8a28a4b0f10337c8
  Stored in directory: /tmp/pip-ephem-wheel-cache-n7mp4vy8/wheels/39/64/23/96a1c4cd5ef480dd890f879c9666c960676c6d3d5eec8b87d4
Successfully built pytube3
[arch2 ~]$ python3
Python 3.8.3 (default, May 17 2020, 18:15:42) 
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pytube import YouTube
>>> yt = YouTube('https://www.youtube.com/watch?v=o-84hC9wgoA')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/pytube/__main__.py", line 92, in __init__
    self.descramble()
  File "/usr/lib/python3.8/site-packages/pytube/__main__.py", line 140, in descramble
    apply_signature(self.player_config_args, fmt, self.js)
  File "/usr/lib/python3.8/site-packages/pytube/extract.py", line 225, in apply_signature
    cipher = Cipher(js=js)
  File "/usr/lib/python3.8/site-packages/pytube/cipher.py", line 31, in __init__
    var, _ = self.transform_plan[0].split(".")
ValueError: too many values to unpack (expected 2)
>>> 

```

**Comment by dhrumil1202** [comment]
well after this change, I get keyError cipher instead of too many values to unpack.

**Comment by Divyansh2512** [comment]
> well after this change, I get keyError cipher instead of too many values to unpack.

Have you changed the key value "cipher" to "signatureCipher" in line 318 of extract.py??

**Comment by dhrumil1202** [comment]
> signatureCipher

Worked!! thanks @Divyansh2512

**Comment by RONNCC** [comment]
Thanks for the contribution @Divyansh2512  :) am merging to unblock master -- 
could you help update tests so we can get CI working again ?

**Comment by jayathungek** [comment]
@belthaZornv nice one, works like a charm! I think the reason the CI build is failing is because you have only placed 1 space between the code and inline comment on line 111 of ```cipher.py```, when the code linter expects 2. Changing that should make the build passing IMO.

**Pull request merged**
