### PR TITLE
Fix for occasional incorrect video title.

### PR DESCRIPTION
**Pull request by jayathungek**
Solves the issue by checking if the text between the ```<title> </title>``` tags in ```watch_html``` is "YouTube". If so, this means that the html was improperly loaded as this text should be "\<video title\> - YouTube". The fix reloads ```watch_html``` by calling ```self.prefetch()``` in a while loop until the correct title is loaded.

### CODE REVIEW

**Comment by jayathungek** [comment]
On second thoughts, realised that the ```<meta property ...>``` tag is better for scraping the video title (thanks to @GrautDevelopes). Separated the title extraction in a different method to make it more readable.

**Review by thechrisandrew — APPROVED** [review]
Tried this fix, seems like fixes my problem sometimes the script return YouTube only as a title

**Comment by RONNCC** [comment]
@jayathungek could you rebase + add a test to confirm functionality 😄  ?

**Comment by jayathungek** [comment]
@RONNCC I've added a test and merged my feature to master :)

**Comment by RONNCC** [comment]
Hi @jayathungek do you mean merged master into your branch?

I'm unfortunately not able to see the test in your code  (https://github.com/nficano/pytube/pull/634/files) -- could it be somewhere else?

**Comment by jayathungek** [comment]
@RONNCC Sorry for the late reply. You should be able to see my changes now

**Comment by tfdahlin** [comment]
@jayathungek I believe that this issue should be resolved by https://github.com/nficano/pytube/pull/775/files, can you confirm if you still have this problem or not so we can close this PR?

**Comment by jayathungek** [comment]
@tfdahlin This is an old PR whose issue has since been fixed, you can close it :)

**Pull request closed without merging**
