### PR TITLE
Custom location of tokens.json, when allow_oauth_cache is True

### PR DESCRIPTION
**Pull request by sayyid5416**
## Current behavior
When `use_oauth=True` and `allow_oauth_cache=True`, oauth tokens are saved in `__cache__` directory inside pytube installed location

## Changes made in this PR
- Ability to set a different location for oauth token than the `__cache__` directory
    - Just pass the `cache_location=<directory path here>`. New tokens would be saved here.
    - If `cache_location=None` _(default behavior)_, `__cache__` location would be used.
    - In this regard, since it may cause some filename issues, file name changed from `tokens.json` to `pytube-tokens.json`.

### CODE REVIEW

**Comment by sayyid5416** [comment]
@glubsy It's been a long time since I've created this PR and there's no response. Neither positive nor negative. Is this pytube project dead or still alive?

**Review by glubsy — APPROVED** [review]
Looks good to me, but have not tested.

**Comment by glubsy** [comment]
@sayyid5416 not sure what is going on with this project, maintainers seem to be busy with life (as I am).

**Comment by sayyid5416** [comment]
@glubsy Aren't you allowed to merge PR?

**Comment by RONNCC** [comment]
👀  happy to review/merge if anyone wants to double check functioning of this commit :-)

**Comment by sayyid5416** [comment]
@RONNCC I've been using these changes a little earlier than opening this PR. Haven't got any issues.

But yeah sure, there is nothing wrong in double checking.

**Comment by RONNCC** [comment]
@sayyid5416  ah apologies i mean after rebasing on master a bit since I merged a few changes there recently

**Review by glubsy — APPROVED** [review]

**Pull request closed without merging**
