### PR TITLE
fixes the 1080p issue

### PR DESCRIPTION
**Pull request by piratimir**
I have done some cleaning in the old code base. For example I created a utility called get_itag to get the itag from a specific url since there was duplicated code to do such stuff I thought it is a better idea to bundle it into a function. The code which deals with the download of the videos/audios streams is also bundled into some function inside the pytube.utility module.

### CODE REVIEW

**Comment by piratimir** [comment]
@nficano Hey man, I just pushed the code. Please check it out 👍

**Review by nficano — APPROVED** [review]
👏 👏 👏

**Comment by nficano** [comment]
@jetbird great job! thanks a lot sir!

**Comment by piratimir** [comment]
@nficano you are welcome man!

**Comment by nficano** [comment]
Why does this need ffmpeg? I'm hesitant to require it as a dependency

**Comment by piratimir** [comment]
@nficano Youtube serves the streams for the 1080p quality separately. I thought to use ffmpeg to join them together, I think youtubedl which is a tool for downloading youtube videos solves this issue with the help of ffmpeg.

**Comment by andreif** [comment]
Why not including even the other resolutions? 

```diff
diff --git a/pytube/api.py b/pytube/api.py
index 558a44d..de41bd9 100644
--- a/pytube/api.py
+++ b/pytube/api.py
@@ -286,3 +286,2 @@ class YouTube(object):
         # Reset the filename incase it was previously set.
-        hd_1080p = False
         self.title = None
@@ -318,7 +317,6 @@ class YouTube(object):
             itag = get_itag(url)
-            if itag == 137:
-                hd_1080p = True
+            if itag in (137, 264, 266):
                 json_object["args"]["stream_map"].get("url").append(url)
             # set the self.audio_url in here
-            if hd_1080p and itag in (140, 171, 249,):
+            if itag in (140, 171, 249,):
                 self.audio_url = url
@@ -476,3 +474,2 @@ class YouTube(object):
             for video in self._videos:
-                if video.resolution == '1080p':
-                    video.audio_url = self.audio_url
+                video.audio_url = self.audio_url
```

Tested with https://www.youtube.com/watch?v=iNJdPyoqt8U

**Comment by andreif** [comment]
Also, I don't really see why you need to go through all PATH directories. If you really need absolute path to ffmpeg or to know if it's available, then you could just run `which ffmpeg` etc. Utility function get_ffmpeg_path (which lives in the class initializer by some reason?) returns None if it does not find ffmpeg, so you need to change the condition to make it work
```diff
diff --git a/pytube/utils.py b/pytube/utils.py
index eb69640..0dcbd85 100644
--- a/pytube/utils.py
+++ b/pytube/utils.py
@@ -36,7 +37,7 @@ class FFMpeg(object):
         self.ffmpeg_path = ffmpeg_path or get_ffmpeg_path()
         # check if ffmpeg_binary is present, if not raise
         # an error
-        if not os.path.exists(self.ffmpeg_path):
+        if not self.ffmpeg_path or not os.path.exists(self.ffmpeg_path):
             raise FFMpegDoesNotExistError('Make sure the ffmpeg binary exists')

     @staticmethod
```

**Comment by andreif** [comment]
```diff
diff --git a/pytube/utils.py b/pytube/utils.py
index eb69640..3c7ad46 100644
--- a/pytube/utils.py
+++ b/pytube/utils.py
@@ -104,7 +105,7 @@ def download_youtube_data(url, path, chunk_size=8*1024,
     # if the path exists and force_overwrite is not True,
     # then raise an exception
     if os.path.exists(path) and not force_overwrite:
-        raise PytubeError('Path already exists')
+        raise PytubeError('Path already exists: %s' % path)
     # open the url for retrieving data
     response = urlopen(url)
     try:
```

**Comment by andreif** [comment]
Audio file path should probably be video path plus some postfix and it's existence checked before downloading video. Currently it can spend some time downloading video part and then fail due to audio path already existing.

**Comment by nficano** [comment]
Found another way to do this, will be releasing this week

**Pull request closed without merging**
