### PR TITLE
Fix bug 20.01.22

### PR DESCRIPTION
**Pull request by lalkalol1907**
pytube.exceptions.RegexMatchError: __init__: could not find match for ^\w+\W

### CODE REVIEW

**Comment by huynguyencong** [comment]
It works for me. Thank you!

**Review by pixselious — APPROVED** [review]
Works for me too. I hope devs approve your request soon.

**Comment by rorysavage77** [comment]
Would really like to see this merged in as the latest version of pytube is completely broken.

**Comment by rorysavage77** [comment]
@pixselious could be please expedite this PR?

**Comment by trong-codelink** [comment]
Somehow the bug is fixed. Pytube now works normally.

**Review by glubsy — CHANGES_REQUESTED** [review]
This PR is not valid anymore. Too many unrelated changes.

**Pull request closed without merging**
