### PR TITLE
Change 'signature' -> 'sig' in generated URL

### PR DESCRIPTION
**Pull request by CraftSpider**
The third and final piece of the 403 error that I can find, submitted as a separate PR because I'm not sure that downloading still works in all cases with this change. Combine with #425 and #426 for the complete fix.

### CODE REVIEW

**Comment by hbmartin** [comment]
@CraftSpider what URLs/video ID required this?

**Comment by RONNCC** [comment]
@CraftSpider  is functionality in this PR still needed? Would be happy to assist in getting it merged

**Comment by CraftSpider** [comment]
This line was fixed some time ago https://github.com/nficano/pytube/blob/ee0deb6dc1c465927472f3c01f8644ddd909ce50/pytube/extract.py#L268 this PR is unneeded

**Comment by RONNCC** [comment]
Thanks @CraftSpider ! :)

**Pull request closed without merging**
