### PR TITLE
Fix: Add support for streaming data to mixins.apply_descrambler

### PR DESCRIPTION
**Pull request by krapes**
This pull request merges a couple of fixes to the mixins.apply_descrambler. Specifically those from @giacaglia [here](https://github.com/nficano/pytube/issues/467#issuecomment-568609340) and @FidoDidoVN [here](https://github.com/nficano/pytube/issues/467#issuecomment-568311609)

It also adds a try - except case for videos that were failing because they didn't have a 'formats' in the stream_data json

### CODE REVIEW

**Comment by Armster15** [comment]
### **Following pull request breaks the `length` and `thumbnail_url` attributes**

Sorry don't know where to post this issue but the following pull request, although it fixes `mixins.apply_descrambler`, it breaks the `thumbnail_url` attribute of the YouTube class and the `length` attribute. The following error logs are pretty much the same.

____

Error log for `thumbnail_url`:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\pytube\__main__.py", line 258, in thumbnail_url
    return self.player_config_args['thumbnail_url']
KeyError: 'thumbnail_url'
```

Error log for `length`:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\pytube\__main__.py", line 299, in length
    return self.player_config_args['length_seconds']
KeyError: 'length_seconds'
```

**Comment by krapes** [comment]
Hey, thanks for the update. Can you post the code you were trying to run when you got those errors?

**Comment by hbmartin** [comment]
@krapes @armaan115 you can pull in fixes from pytube3 for these issues

**Comment by Armster15** [comment]
LOL I just fixed the error as well, you guys can pull in the fixes: https://github.com/armaan115/pytube-568.git

**Pull request merged**
