### PR TITLE
fix pytube issues 387 

### PR DESCRIPTION
**Pull request by minwook-shin**
fix KeyError: 's' Error.
https://github.com/nficano/pytube/issues/387

### CODE REVIEW

**Comment by partriv** [comment]
this fixed https://github.com/nficano/pytube/issues/400

**Comment by adamknight84** [comment]
Can this fix be released? It seems to be causing the majority of videos to fail.

**Comment by ndg63276** [comment]
I still have problems with lsig. This works better for me:
```
    for i, stream in enumerate(stream_manifest):
        if 'url' in stream:
            url = stream['url']
        elif live_stream:
            raise LiveStreamError('Video is currently being streamed live')

        if ('signature=' in url) or ('&sig=' in url):
            # For certain videos, YouTube will just provide them pre-signed, in
            # which case there's no real magic to download them and we can skip
            # the whole signature descrambling entirely.
            logger.debug('signature found, skip decipher')
            continue

        if js is not None:
            try:
                signature = cipher.get_signature(js, stream['s'])
            except:
                continue
        else:
            # signature not present in url (line 33), need js to descramble
            # TypeError caught in __main__
            raise TypeError('JS is None')

        logger.debug(
            'finished descrambling signature for itag=%s\n%s',
            stream['itag'], pprint.pformat(
                {
                    's': stream['s'],
                    'signature': signature,
                }, indent=2,
            ),
        )
        stream_manifest[i]['url'] = url + '&sig=' + signature
```

**Comment by naseemrafique** [comment]
When this change will be released. I am using 9.5.0.

**Comment by Qu4tro** [comment]
Why was this PR closed @nficano ? Latest release seems to be affected by this issue.

**Pull request closed without merging**
