### PR TITLE
Fixed 'title' KeyError and 403 forbidden issues on signed videos

### PR DESCRIPTION
**Pull request by bigg215**
Implemented suggestions to fix 'title' KeyError and 403 forbidden issues when dealing with protected/signed videos (seems to be any video tagged as music by YouTube).

### CODE REVIEW

**Review by AbhishekVarshney98 — APPROVED** [review]
Thanks, man!! These changes literally worked for me.

**Comment by danguddemi** [comment]
These fixes solved the issue on my end
Running `python3.7.3` on `Pop-OS`

**Review by iamwalter — COMMENTED** [review]
These changes solved the HTTP 403 Forbidden problem for me.

**Comment by allen108108** [comment]
I change codes but have another error 

`bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?`

How can I solve it ?

**Comment by danguddemi** [comment]
> I change codes but have another error
> 
> `bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?`
> 
> How can I solve it ?

This is a BeautifulSoup question not PyTube.
Beautiful Soup is just the interface and you have to install a parser library to actually use it.
LXML is a XML/HTML processing library that you chose to use. 
It should be as simple as `pip install lxml`

**Comment by Midlight25** [comment]
How do I integrate this into my existing pytube installation. (I'm just starting out as a github user so I'm not quite sure how everything works.

**Comment by danguddemi** [comment]
> How do I integrate this into my existing pytube installation. (I'm just starting out as a github user so I'm not quite sure how everything works.

You have to apply the changes directly to the source code. This is easy since Python doesn't compile.
 **Assuming that you're using a virtual environment (you should be)**

1. Traverse the virtual environment directory : <venv name>/lib/python<version>/site-package/pytube
2. Modify the necessary files with the code in this PR
3. Save the files and you're done!

**Review by danguddemi — CHANGES_REQUESTED** [review]
You have styling errors that need to be fixed.
https://travis-ci.org/nficano/pytube/jobs/572573240

**Comment by danguddemi** [comment]
> How do I integrate this into my existing pytube installation. (I'm just starting out as a github user so I'm not quite sure how everything works.

Anyone who wants to install this patch without modifying the files themselves can also just run
`pip install -e git+https://github.com/bigg215/pytube.git#egg=pytube`

This will install the PyTube implementation in that repo and still allow you to `pip freeze > requirements.txt`

**Comment by allen108108** [comment]
About one  month ago ,  I use this #453 to fix pytube.
Yesterday I want use #453 to fix pytube in my new env. that I failed. Anyone knows is that a new proplem ?

**Comment by mf1611** [comment]
> About one month ago , I use this #453 to fix pytube.
> Yesterday I want use #453 to fix pytube in my new env. that I failed. Anyone knows is that a new proplem ?

I had also the same problem.

**Comment by hbmartin** [comment]
@mf1611 fixed in pytube3: https://github.com/hbmartin/pytube3

**Pull request merged**
