### PR TITLE
Fixes unescaped html in Youtube.title

### LINKED ISSUE #498: when using title i get the name but also with some garbage
when trying to get the title in hebrew of this: https://www.youtube.com/watch?v=g4t2GDIoquE
I get some garbage with it.

Capture

### PR DESCRIPTION
**Pull request by flexiblestoic**
Fixes #498. 

It is my first pull so... not sure I did it correctly. Thanks.

### CODE REVIEW

**Comment by hbmartin** [comment]
@flexiblestoic can you provide an example URL that this fix works for?

**Comment by flexiblestoic** [comment]
@hbmartin Sure, please see: https://github.com/nficano/pytube/issues/498#issuecomment-555053152

**Comment by hbmartin** [comment]
@flexiblestoic  added this to my Python 3 only fork: https://github.com/hbmartin/pytube3

**Comment by RONNCC** [comment]
Issue seems to be fixed already -- please re-open if this isn't the case :)

**Pull request closed without merging**
