### PR TITLE
 Fix nficano#467 KeyError: 'url_encoded_fmt_stream_map' 

### PR DESCRIPTION
**Pull request by swiftyy-mage**
Looks like @FidoDidoVN had the same idea as me a few days ago, but it was posted on an issue from September so I only saw it after I made the fix. Still I guess credit has to go to them.

### CODE REVIEW

**Comment by aliakseis** [comment]
Hi, sorry, it looks like not all runtime errors are fixed yet:
https://github.com/swiftyy-mage/pytube/blob/88b1c9da1a69a78d042dc8ffe9699de3f15b79a0/pytube/mixins.py#L10

**Comment by swiftyy-mage** [comment]
Don't apologize I really shouldn't find it so difficult to import modules. It's because I didn't copy/paste the whole file from my version, I just edited the fork which leads me to forget simple stuff. Should be working fine now.

**Comment by swiftyy-mage** [comment]
Had to make a 4th commit because the 3rd was submitted from my phone and it capitalized the F in `from pytube.compat`

**Comment by matthyx** [comment]
@nficano can you merge this PR and release still this year? I am facing the same issue and would like a permanent fix, thanks!

**Review by wendeldr — APPROVED** [review]

**Comment by neneone** [comment]
Thank you, this worked for me. @nficano could you please merge this?

**Comment by yanivohayon8** [comment]
Hi,
For me the error (KeyError: 'url_encoded_fmt_stream_map') is keep showing up.
At first I tried to update the package using the following command:
pip install pytube -U

The package was successfully upgraded to 9.5.3 version, but the same error continue to rise.
At next, I tried to install the package base on 2 commit:

1.  The last commit (66b33803adb1780a84c7cf75ab8968bd5f0fcffc )  -> still having the same error
2.  The commit that should fix the problem according to what  I read in [StackOverflow](https://stackoverflow.com/questions/59135180/keyerror-url-encoded-fmt-stream-map)
(e5f1a9e2476b096ed2012939d50851d3499016e1), throwing :

"fatal: reference is not a tree: e5f1a9e2476b096ed2012939d50851d3499016e1
ERROR: Command errored out with exit status 128: git checkout -q e5f1a9e2476b096ed2012939d50851d3499016e1 Check the logs for full command output."

The command I have used is the following:
pip install -e git+https://github.com/nficano/pytube@e5f1a9e2476b096ed2012939d50851d3499016e1#egg=pytube

I have tried several time to reinstall the package without any success to get rid of the error(pip install --upgrade --force-reinstall)

I Appreciate your help!

**Comment by ir0nt0ad** [comment]
@nficano would be great if you could merge, thanks

**Comment by economy** [comment]
LGTM, this solution worked for me!

**Comment by ghost** [comment]
This solution works for me.

**Comment by GrautDevelopes** [comment]
Thanks, this fixed my issues. Please merge, @nficano

**Comment by Raanger99** [comment]
Worked perfectly for me as well.
Windows 10, Python 3.8.1
Great thanks!

**Comment by hbmartin** [comment]
fixed in my Python 3 only fork: https://github.com/hbmartin/pytube3

**Comment by swiftyy-mage** [comment]
Looking good! I'll take a closer look later today after work.

**Comment by sebpiq** [comment]
Merge would be awesome :) no pressure

**Comment by aalokkeshri** [comment]
Getting the Error 
Keyerror :"url"

The URL having having underscore is facing the issue

**Comment by RONNCC** [comment]
Issue seems to be fixed already -- please re-open if this isn't the case :)

**Pull request closed without merging**
