### PR TITLE
https://github.com/nficano/pytube/issues/434

### PR DESCRIPTION
**Pull request by ndg63276**
Fix for issue #434

### CODE REVIEW

**Comment by heckad** [comment]
It is not a solution. It just hides the problem.

**Review by LaGamma — APPROVED** [review]
These changes fix the issue - please merge them!

**Review by TheR1D — APPROVED** [review]

**Comment by hbmartin** [comment]
@ndg63276 @TheR1D @LaGamma  fixed in my Python 3 only fork: https://github.com/hbmartin/pytube3

**Comment by RONNCC** [comment]
Issue seems to be fixed already -- please re-open if this isn't the case :)

**Pull request closed without merging**
