### PR TITLE
Fix not generating the signature when `lsig` is present

### PR DESCRIPTION
**Pull request by CraftSpider**
This only fixes one part of the 403 error, #425 is required to fix regex not matching, and line 64 needs 'signature' replaced with 'sig' in some cases

Combining this with the other two fixes, I'm no longer getting any error 403

### CODE REVIEW

**Comment by hbmartin** [comment]
@CraftSpider what URLs/video ID required this?

**Comment by CraftSpider** [comment]
Thank you for your patience. Its been a long time, and I don't remember exactly. I made my two PRs as 'This fixed my issue and didn't introduce any I saw'. I know adding the prefix to sig was because there could exist an `lsig` param, and checking for `sig=` would incorrectly conclude it existed because that overlaps with `lsig=`, I will try some links and update my PR if I can find a still broken one, otherwise close them out

**Comment by RONNCC** [comment]
@CraftSpider  is functionality in this PR still needed? Would be happy to assist in getting it merged

**Comment by CraftSpider** [comment]
This line was fixed some time ago
https://github.com/nficano/pytube/blob/ee0deb6dc1c465927472f3c01f8644ddd909ce50/pytube/extract.py#L254
this PR is unneeded

**Comment by RONNCC** [comment]
Thanks @CraftSpider 

Would love your assistance with other bugs/issues that you may run into -- definitely appreciate the PR!

**Pull request closed without merging**
