### PR TITLE
Updated setup.py to reflect current state of the project.

### PR DESCRIPTION
**Pull request by tfdahlin**
A while back, when this repository was beginning to fall out of maintenance, hbmartin forked the repo and began maintaining that. Many of these commits were eventually merged into nficano's repository, including changes to the setup file which link back to hbmartin's repository. This reverts those changes in the setup.py file to reflect the current state of this project.

### CODE REVIEW

**Comment by tfdahlin** [comment]
@ronncc what's the process for getting a PR reviewed/merged?

**Comment by RONNCC** [comment]
@tfdahlin Usual -- make PR, add tests, and ping me if needed 😄

**Comment by jugmac00** [comment]
Linting fails on this pr...

```
./setup.py:26:96: E501 line too long (97 > 95 characters)
./pytube/cipher.py:111:118: E261 at least two spaces before inline comment
Makefile:43: recipe for target 'ci' failed
make: *** [ci] Error 1
```

**Comment by RONNCC** [comment]
@jugmac00  could you help to fix it and submit a PR

**Comment by jugmac00** [comment]
@RONNCC Sure, here we go: https://github.com/tfdahlin/pytube/pull/1

As I cannot edit the PR here (I am no maintainer), and of these two linter errors, one was introduced by this PR, I had to create a PR against @tfdahlin s PR at his repo.

Either @tfdahlin merges my PR, or you merge his PR and then I set another target for my PR or you just apply the changes directly to his PR (when he permitted edit) or you do the changes afterwards via GitHub UI:

https://github.com/tfdahlin/pytube/pull/1/files

**Comment by tfdahlin** [comment]
Must have missed Ronnie's response to my PR before, my bad.
@jugmac00 merged your PR; @RONNCC take a look at this and merge it perhaps?

**Comment by RONNCC** [comment]
@tfdahlin  could you just test HEAD /w your changes does work for a basic download a youtube video test 😄  -- ideally we would have a CI integration test for that but think we are a bit off from that still

**Comment by tfdahlin** [comment]
Following the example in the repo's readme, with my branch of pytube installed:

image

**Comment by tfdahlin** [comment]
cc: @RONNCC

**Comment by RONNCC** [comment]
Merged @tfdahlin 

Can you update https://python-pytube.readthedocs.io/en/latest/user/install.html also -- Pytube != Pytube3 as they're maintained by different orgs 

Also feel free to ping me multiple times if needed - sometimes I miss pings in longer threads

**Pull request merged**
