### PR TITLE
Domain switch

### PR DESCRIPTION
**Pull request by logston**

### CODE REVIEW

**Comment by zerok** [comment]
Should we perhaps somehow first really check all links on pyvideo that they can be mapped directly to pytube? How will we deal with broken links?

**Comment by codersquid** [comment]
@zerok for broken links one way to deal with it is for user to open an issue, and better would be getting 404 information from logs (if possible). I'm not familiar if one can get that info from github pages. Maybe it can come from google analytics?

**Comment by zerok** [comment]
Personally, I'd prefer if we could test that offline first :)

**Comment by codersquid** [comment]
@zerok I see... could do both. It's good to monitor that stuff if possible.

I'd like to see this landed asap so that people who visit pyvideo.org don't have the notice without being directed where to go. I'm willing to risk 404s. I suggest maybe timeboxing the testing such that, if someone can write a script soon to hit the pyvideo urls to check that they don't get 404s, then great, but if a few days go past, then land anyway.

**Comment by logston** [comment]
@zerok I'd like to test as much as possible also but @codersquid makes a great point that this testing should be time limited. People at the PSF are starting to ask that pyvideo.org get switch over soon. Also, fyi, I've tested a few links by hand. 

I'm going to merge this in as it does not effect any current functionality (on pyvideo.org of course), nor on pytube. The banner will go up but that will not limit usage of the core utilities of the site; watching videos. 

Let's go live with the redirect Friday. @zerok If you have a script to test the pytube's aliases before then, that'd be great. If not, no worries as we can add a JS snippet to our 404 page that will ping a webhook. That'll will have to be built out a bit but a small google apps app should be able to handle it.

**Pull request merged**
