### PR TITLE
Fixed KeyError "title"

### PR DESCRIPTION
**Pull request by jonathanhanley**
Fixed the keyword error in streams.py

### CODE REVIEW

**Comment by jonathanhanley** [comment]
Fixed KeyError title

**Comment by hbmartin** [comment]
@jonathanhanley can you provide an example URL demonstrating the need for this fix?

**Comment by jonathanhanley** [comment]
I can't remember exactly what the issue was it was so long ago but as far as I remember it wouldn't download any video because of an error when accessing some data in a dictionary. I tested the code after the change and it worked before I committed. I hope this helps :)

**Comment by jonathanhanley** [comment]
Feel free to send me a message and I might be able to help 👍

**Comment by hbmartin** [comment]
@jonathanhanley fixed in my Python 3 only fork: https://github.com/hbmartin/pytube3

**Pull request closed without merging**
