### PR TITLE
Fix bug video_info_url HTTP 404 Error

### PR DESCRIPTION
**Pull request by Ssuwani**

### CODE REVIEW

**Review by iim-ayush — APPROVED** [review]
Now it is working fine. Thanks

**Comment by supermomie** [comment]
work perfectly !!!

**Comment by DmitryCherneckiy** [comment]
Works great, thank you!
@tfdahlin please, add this fix to the pytube library.

**Comment by Mitzuka** [comment]
Like magic, it works to me. 
Thank you. :D

**Review by Mitzuka — APPROVED** [review]
Tested in W10 and Ubuntu 
Python 3.9.4
pytube 10.8.1

It works to me.

**Comment by tfdahlin** [comment]
Closing this in favor of #998 for coding convention

**Pull request closed without merging**
