### PR TITLE
Fast forward data dir

### PR DESCRIPTION
**Pull request by logston**

### CODE REVIEW

**Comment by logston** [comment]
Not sure what happened. Not merging this because all PyCon US 2016 and PythonBrasil videos are listed in an undefined event. See preview.pytube.org for details. Will investigate later.

**Comment by Daniel-at-github** [comment]
Anything to do with this errors?:
~~~
make VERBOSE=1 html

WARNING: Feeds generated without SITEURL set properly may not be valid
ERROR: Could not process conferences/pycon-us-2013/posters/apsimregions-a-gridded-modeling-framework-for-th.json
  | KeyError: 'type'
ERROR: Could not process conferences/.schemas/video.json
  | KeyError: 'type'
WARNING: There are 2 variants of "how-do-debug-tool-bars-for-web-applications-work" with lang en
WARNING: 	~/git/pytube/content/conferences/djangocon-2014/videos/how-do-debug-tool-bars-for-web-applications-work.json
WARNING: 	~/git/pytube/content/conferences/pycon-au-2014/videos/how-do-debug-tool-bars-for-web-applications-work.json
WARNING: There are 3 variants of "lightning-talks" with lang en
WARNING: 	~/git/pytube/content/conferences/djangocon-2015/videos/lightning-talks.json
WARNING: 	~/git/pytube/content/conferences/djangocon-2014/videos/lightning-talks.json
WARNING: 	~/git/pytube/content/conferences/kiwi-pycon-2009/videos/lightning-talks.json
WARNING: There are 2 variants of "pythons-new-type-hints-in-action-in-javascript" with lang en
WARNING: 	~/git/pytube/content/conferences/kiwi-pycon-2015/videos/pythons-new-type-hints-in-action-in-javascript.json
WARNING: 	~/git/pytube/content/conferences/pycon-ca-2015/videos/pythons-new-type-hints-in-action-in-javascript.json
Done: Processed 3967 articles, 0 drafts, 1 page and 1 hidden page in 88.73 seconds.
~~~

**Comment by logston** [comment]
Maybe, @Daniel-at-github. Looking into it now.

**Comment by logston** [comment]
Looks like this has to do with me monkey patching the ArticleGenerator. 
https://github.com/pytube/pytube/blob/master/plugins/drop_no_publish.py#L46

Stil investigating.

**Comment by logston** [comment]
Found this issue. These new videos are defined in the new schema that makes "category" deprecated. We need to pull the category for each file from the `category.json` file.

**Pull request merged**
