### PR TITLE
Fix #1082

### LINKED ISSUE #1082: [BUG] Getting KeyError while searching a query
I'm trying to get the first video by searching it by name using Search class.
Code example:
```
from pytube import Search
print(Search('music').results[0].watch_url)
```
But i'm getting:
```
Traceback (most recent call last):
  File "D:\Apps\Python\lib\site-packages\pytube\contrib\search.py", line 94, in
fetch_and_parse
    sections = raw_results['contents']['twoColumnSearchResultsRenderer'][
KeyError: 'twoColumnSearchResultsRenderer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Downloads\Python Programs\Discord-Bot\src\tester.py", line 2, in <mod
ule>
    print(Search('music').results[0].watch_url)
  File "D:\Apps\Python\lib\site-packages\pytube\contrib\search.py", line 62, in
results
    videos, continuation = self.fetch_and_parse()
  File "D:\Apps\Python\lib\site-packages\pytube\contrib\search.py", line 97, in
fetch_and_parse
    sections = raw_results['onResponseReceivedCommands'][0][
KeyError: 'onResponseReceivedCommands'

Process finished with exit code 1
```
It seems to be a bug.

python version: 3.9.1
pytube version: 11.0.0

### PR DESCRIPTION
**Pull request by priamoryki**
I may have managed to solve #1082. Please test, and write if there are any nuances 😶

### CODE REVIEW

**Comment by jimmyjohnjr1203** [comment]
Tried your fix for #1082 and it seems to work when pulling the Search().results property however get_next_results() returns an IndexError:

```python
>>> from pytube import Search 
>>> search = Search('test')
>>> search.results
[<pytube.__main__.YouTube object: videoId=Kt8RupLIkBQ>, 
<pytube.__main__.YouTube object: videoId=GAlRLwyEJIU>, 
<pytube.__main__.YouTube object: videoId=YAxLueEKqmU>, 
<pytube.__main__.YouTube object: videoId=MPxpDtaPHvA>,
<pytube.__main__.YouTube object: videoId=pyKmVy2TC2E>, 
<pytube.__main__.YouTube object: videoId=TnC2lAbyD0w>, 
<pytube.__main__.YouTube object: videoId=9bDUC3DFiOE>, 
<pytube.__main__.YouTube object: videoId=tpLLst4-3fw>]
>>> search.get_next_results()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jackl\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\contrib\search.py", line 77, in get_next_results
    raise IndexError
IndexError

**Comment by priamoryki** [comment]
It seems to be working now. But I don't like the code at all.

**Comment by priamoryki** [comment]
I noticed that not all itemSectionRenderers are parsed. Fixed now.

**Comment by jimmyjohnjr1203** [comment]
Tried your changes and haven't been able to get any errors so it's working for me. Thanks.

**Comment by rfma23** [comment]
Tried the changes and it works for me as well, thanks

**Comment by tfdahlin** [comment]
Closing this because it should be handled by #1090 in v11.0.1

**Pull request closed without merging**
