### PR TITLE
Added functionality to only parse a set amount of links

### PR DESCRIPTION
**Pull request by Choromanski**
Allows parsing of partial playlist

### CODE REVIEW

**Comment by hbmartin** [comment]
@Choromanski are there any tests for this?

**Comment by Choromanski** [comment]
Honestly not even sure if this works anymore.
I'll look into it and make up some tests. Hopefully some time this weekend.

**Comment by hbmartin** [comment]
I made a PR for pytube3 that does almost the same thing https://github.com/hbmartin/pytube3/pull/26 except using a video id instead of an index

**Comment by RONNCC** [comment]
Issue seems to be fixed already -- please re-open if this isn't the case :)

**Pull request closed without merging**
