### PR TITLE
Fix of new signature deciphering

### PR DESCRIPTION
**Pull request by johnberroa**
#312 
It seems a lot of people are getting this error because youtube changed its signature deciphering method  (as pointed out by @anxdpanic).  It's a hacky fix but it will get the program running:  I  took the regex patterns mentioned in #312 and put them in a list that it steps through to check.   Feel free to make it prettier!

### CODE REVIEW

**Review by nficano — APPROVED** [review]

**Comment by BishopKO** [comment]
johnberroa bless You.:)

**Comment by Ikebani** [comment]
I changed the pattern in cipher.py but it still isn't working, any help?

**Comment by ytensor42** [comment]
Is this fixed? I just have installed latest version (9.3.4) from this repo and still got regex error.

$ pytube https://www.youtube.com/watch?v=<somevideohere> --list

.
.
.

anaconda/lib/python3.6/site-packages/pytube-9.3.4-py3.6.egg/pytube/helpers.py", line 41, in regex_search
pytube.exceptions.RegexMatchError: regex pattern (yt\.akamaized\.net/\)\s*\|\|\s*.*?\s*c\s*&&\s*d\.set\([^,]+\s*,\s*(?P<sig>[a-zA-Z0-9$]+)\() had zero matches

**Comment by PekaryGergelyR** [comment]
**I fixed it by adding the following pattern :**
`r'\bc\s*&&\s*d\.set\([^,]+,.*?\((?P<sig>[a-zA-Z0-9$]+)\(\(0\s*,\s*window.decodeURIComponent'`

**in the get_initial_function_name:**
```
def get_initial_function_name(js):
    """Extract the name of the function responsible for computing the signature.

    :param str js:
        The contents of the base.js asset file.

    """
    # c&&d.set("signature", EE(c));
    pattern = [
        r'\bc\s*&&\s*d\.set\([^,]+,.*?\((?P<sig>[a-zA-Z0-9$]+)\(\(0\s*,\s*window.decodeURIComponent',
        r'yt\.akamaized\.net/\)\s*\|\|\s*'
        r'.*?\s*c\s*&&\s*d\.set\([^,]+\s*,\s*(?P<sig>[a-zA-Z0-9$]+)\(',
        r'\.sig\|\|(?P<sig>[a-zA-Z0-9$]+)\(',
        r'\bc\s*&&\s*d\.set\([^,]+\s*,\s*(?P<sig>[a-zA-Z0-9$]+)\(',
    ]
    logger.debug('finding initial function name')
    return regex_search(pattern, js, group=1)```

**Comment by Cupprum** [comment]
For everyone who didnt understand @GulyasGergelyR fix you have copy his code and replace it in pytube/cipher.py

**Comment by danys94** [comment]
> **I fixed it by adding the following pattern :**
> `r'\bc\s*&&\s*d\.set\([^,]+,.*?\((?P<sig>[a-zA-Z0-9$]+)\(\(0\s*,\s*window.decodeURIComponent'`
> 
> **in the get_initial_function_name:**
> 
> ```
> def get_initial_function_name(js):
>     """Extract the name of the function responsible for computing the signature.
> 
>     :param str js:
>         The contents of the base.js asset file.
> 
>     """
>     # c&&d.set("signature", EE(c));
>     pattern = [
>         r'\bc\s*&&\s*d\.set\([^,]+,.*?\((?P<sig>[a-zA-Z0-9$]+)\(\(0\s*,\s*window.decodeURIComponent',
>         r'yt\.akamaized\.net/\)\s*\|\|\s*'
>         r'.*?\s*c\s*&&\s*d\.set\([^,]+\s*,\s*(?P<sig>[a-zA-Z0-9$]+)\(',
>         r'\.sig\|\|(?P<sig>[a-zA-Z0-9$]+)\(',
>         r'\bc\s*&&\s*d\.set\([^,]+\s*,\s*(?P<sig>[a-zA-Z0-9$]+)\(',
>     ]
>     logger.debug('finding initial function name')
>     return regex_search(pattern, js, group=1)```
> ```

Oh man, that didn't worked for me :( 

`$ ./ydown.py --dest /home/dcech/Music/ --link https://youtu.be/XTfvtqgONHA?list=PLtKjnWHrSxlNVWOJsQPzHOifjWcCeSUq-
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pytube/__main__.py", line 131, in init
    mixins.apply_signature(self.player_config_args, fmt, self.js)
  File "/usr/local/lib/python3.6/dist-packages/pytube/mixins.py", line 41, in apply_signature
    signature = cipher.get_signature(js, stream['s'])
  File "/usr/local/lib/python3.6/dist-packages/pytube/cipher.py", line 249, in get_signature
    tplan = get_transform_plan(js)
  File "/usr/local/lib/python3.6/dist-packages/pytube/cipher.py", line 68, in get_transform_plan
    name = re.escape(get_initial_function_name(js))
  File "/usr/local/lib/python3.6/dist-packages/pytube/cipher.py", line 45, in get_initial_function_name
    return regex_search(pattern, js, group=1)
  File "/usr/local/lib/python3.6/dist-packages/pytube/helpers.py", line 34, in regex_search
    regex = re.compile(pattern, flags)
  File "/usr/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.6/re.py", line 289, in _compile
    p, loc = _cache[type(pattern), pattern, flags]
TypeError: unhashable type: 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./ydown.py", line 11, in <module>
    yt = YouTube(args.link)
  File "/usr/local/lib/python3.6/dist-packages/pytube/__main__.py", line 87, in __init__
    self.prefetch_init()
  File "/usr/local/lib/python3.6/dist-packages/pytube/__main__.py", line 96, in prefetch_init
    self.init()
  File "/usr/local/lib/python3.6/dist-packages/pytube/__main__.py", line 134, in init
    self.embed_html, self.age_restricted,
  File "/usr/local/lib/python3.6/dist-packages/pytube/extract.py", line 126, in js_url
    ytplayer_config = get_ytplayer_config(html, age_restricted)
  File "/usr/local/lib/python3.6/dist-packages/pytube/extract.py", line 174, in get_ytplayer_config
    yt_player_config = regex_search(pattern, html, group=1)
  File "/usr/local/lib/python3.6/dist-packages/pytube/helpers.py", line 39, in regex_search
    .format(pattern=pattern),
pytube.exceptions.RegexMatchError: regex pattern (;ytplayer\.config\s*=\s*({.*?});) had zero matches
`

**Comment by Muni-Royal-King** [comment]
> For everyone who didnt understand @GulyasGergelyR fix you have copy his code and replace it in pytube/cipher.py

want_download == True:
                            print(f'Downloading: {playlist.title}')
                            print(f'Downloading ... 720p ...{video.title}')
                            YouTube(url,on_progress_callback=on_progress) #got error here , iam use this for gettion progress bar so i got error here
                            video.streams.get_by_itag(22).download(filename=f'{counter} - {videoTitle}', output_path=f'{fileLocation}')
                            print(f'Download Completed:- {video.title}')

i got error 
advance thanks

**Pull request merged**
