### PR TITLE
Fix for #763

### PR DESCRIPTION
**Pull request by tfdahlin**
Preliminary fix for issue #763, I'm no longer running into problems with this change. Changes how the `base.js` path is fetched, instead of relying on the ytplayer config.

### CODE REVIEW

**Comment by tfdahlin** [comment]
cc: @RONNCC

**Comment by tfdahlin** [comment]
Ugh, looks like the unit test doesn't work correctly with this, might need to update one of those mocks

**Comment by delrius-euphoria** [comment]
Copied and pasted this extract.py, fixed the key error for me.

**Comment by mmorykan** [comment]
Fixed the key error for me. Thank you very much

**Comment by antoninodimaggio** [comment]
This works. Good looks.

**Comment by jihuun** [comment]
Works for me, Thanks!

**Comment by omarg6773** [comment]
it fixed but i got another error 
SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' on line 291
can u help me pls

**Comment by omarg6773** [comment]
it works but why i can't download videos with high quality some videos has  720p,360p  but most of them has only low quality, Thanks in advance.

**Comment by imanhpr** [comment]
is it work on pytube3 ?

**Comment by tfdahlin** [comment]
@omarg6773 not all videos have high quality versions. Chances are, the videos you're trying to download simply don't have high quality versions, as this library should be able to download the highest quality available.

@imanhpr pytube3 is not the same as pytube (this repo); pytube3 was a fork of this repository that was maintained for a little while, then stopped being maintained after being merged back into this repository. When my PR is merged, you will need to install pytube, not pytube3.

**Comment by imanhpr** [comment]
@tfdahlin i was instawhen I was using pytube3 everything works fine except this [#763](https://github.com/nficano/pytube/issues/763) issue but now I install pytube for my project and I saw a new error that I don't know how can I fix it.
ModuleNotFoundError: No module named 'pytube'
so I checked installed packages on pipenv environment and i confirms that pytube install in it but i don't know why this happens.
so I find a solution in ["ImportError: cannot import name 'quote' from 'pytube.compat' #591"](https://github.com/nficano/pytube/issues/591) issue but it's not updated.

**Comment by imanhpr** [comment]
@tfdahlin when I was using pytube3 everything works fine except this [#763](https://github.com/nficano/pytube/issues/763) issue but now I install pytube for my project and I saw a new error that I don't know how can I fix it.
ModuleNotFoundError: No module named 'pytube'
so I checked installed packages on pipenv environment and i confirms that pytube install in it but i don't know why this happens.
so I find a solution in [#591](https://github.com/nficano/pytube/issues/591) issue but it's not updated.

**Comment by tfdahlin** [comment]
@imanhpr right now, the most current version of this code is not available through pypi -- it's been a while since the code from this repo got pushed there (i.e. this code isn't available by using `pip install pytube`). 

If you want to install my fix for this problem, I would recommend that you first run `pip uninstall pytube` and `pip uninstall pytube3`, then you will have to use `python -m pip install git+https://github.com/tfdahlin/pytube@909c44f8c85c9c13145fe8dd081ed880f45d1752` for now. 

Later on, my fix will be merged to this repository, and you will be able to use `python -m pip install git+https://github.com/nficano/pytube`, but that won't work for the time being.

**Comment by tfdahlin** [comment]
cc: @RONNCC again, would be great to get this merged

**Comment by danthedanman** [comment]
Awesome fix -- thank you!  Hope it gets merged soon, but instruction for installing from your branch very helpful.

**Comment by RONNCC** [comment]
@tfdahlin sg -- can you change "            "PSY - GANGNAM STYLE(강남스타일) MV.mp4"" to less controversial YT video 😆 
i'm thinking of #774 

LGTM Otherwise -- sorry I don't code much on weekends

**Comment by tfdahlin** [comment]
@RONNCC I absolutely can do that, but that will have to be part of another PR, *after* this one gets merged. I wrote an addition to `helpers.py` that makes creating new mock tests relatively easy, but it's a pain in the rear to properly test because of the platform-specific unit tests, and switching back and forth is messy. I'm more than happy to make those changes after this gets merged though.

**Comment by RONNCC** [comment]
@tfdahlin  sounds good

**Comment by drwjf** [comment]
Now it need almost 2 minutes to parse out URLs.

**Comment by Myphz** [comment]
It works! Thank you, you are amazing!

**Comment by 5mbl** [comment]
where I need do copy  `this python -m pip install git+https://github.com/nficano/pytube` ? In my CMD? In my CMD it does not work

**Comment by RONNCC** [comment]
@5mbl  normal installing from PIP should work - the above is not needed anymore

**Comment by delrius-euphoria** [comment]
@RONNCC  Whats the normal pip command? pip install pytube3 ? or just the pytube?

**Comment by RONNCC** [comment]
@nihaalnz  just `pip install pytube`. Pytube3 is a different library haha 😄

**Comment by delrius-euphoria** [comment]
@RONNCC  It was actually for a Q [here](https://stackoverflow.com/questions/64932947/i-have-python-application-with-pytube-and-tkinter/64933190#64933190)

**Comment by tfdahlin** [comment]
@nihaalnz for reference, in the past, pytube got forked to pytube3, and pytube3 got forked to pytubex, so there's a mix of users with many different installations of conflicting pytube libraries.

Generally, I recommend that people run `python -m pip uninstall pytube pytube3 pytubex` to make sure that all the conflicting libraries are uninstalled, then run either `python -m pip install pytube` (to get from pypi) or `python -m pip install git+https://github.com/nficano/pytube` (to get from the repo). 

For reference on why `python -m pip install` instead of `pip install`, see [this article](https://adamj.eu/tech/2020/02/25/use-python-m-pip-everywhere/)

**Comment by delrius-euphoria** [comment]
@tfdahlin  Thanks bruh!!,

**Comment by manuredd** [comment]
@tfdahlin so I uninstalled pytube, pytube3, and pytubeX as you said. Then I ran "python -m pip install pytube" and it was successful. However, it says the scripture is installed in "/users/manu/library/python/2.7/bin which is not on PATH." Is this an issue if I am using python 3.9 as the interpreter? Also, do I need to worry about the "which is not in path" part? Thanks and sorry if my questions are dumb, i am new to this 😅 btw i am on mac

**Comment by tfdahlin** [comment]
hi @manuredd I think the issue you're running into is that you have both python2 and python3 installed on your system (the mac I use for work has the same issue). If you run "python --version", does it say its python 2.7.x? 

If so, you may instead need to run the following commands:
`python3 -m pip uninstall pytube pytube3 pytubex`
`python3 -m pip install pytube`

By running `python -m pip install pytube`, you are most likely installing pytube for the python 2.7 interpreter, and *not* your python 3.9 interpreter.

**Pull request merged**
