### PR TITLE
Temporary file extension fix when ffmpeg is involved

### PR DESCRIPTION
**Pull request by hftsai256**
Addressing existing issue #1109 by removing unnecessary extensions in temporary filenames.

### CODE REVIEW

**Comment by ethaizone** [comment]
Confirmed that this PR can fix this issue on Windows.

**Comment by unaimillan** [comment]
Please approve this pull request 🙏

**Comment by Axer128** [comment]
Looks like it would fix the issue, should be approved

**Comment by Juodvarnis-As** [comment]
This branch works perfectly, as I had some WinError 2 problems with FFMPEG. Should be approved.

**Pull request closed without merging**
