### PR TITLE
Fix KeyError: 'start' in function generate_srt_captions()

### PR DESCRIPTION
**Pull request by Sovenok-Hacker**
Fix issue #1085

### CODE REVIEW

**Comment by anAwesomeWave** [comment]
Your solution doesn't work for me. I get an empty string with it

**Review by Davidtsang — COMMENTED** [review]
fix sub

**Comment by ghost** [comment]
Is there a way to reproduce the issue?

**Comment by Sovenok-Hacker** [comment]
To Reproduce
Here is the code I am trying to test:

import pytube
from pytube import Playlist, YouTube

url = "https://www.youtube.com/watch?v=vKA4w2O61Xo&list=PLkahZjV5wKe8WFEwvs69V7JO-Cx57rZ8W"
p = Playlist(url)

for v in p.videos[:3]:
    print("trying to get captions for:", v.title)
    print(v.captions["a.en"].generate_srt_captions())
This code used to print the caption before updating pytube, but now it breaks

(From #1085)

**Comment by hunghoang-saritasa** [comment]
Your solution doesn't work for me

Step to reproduce:
- url: https://www.youtube.com/watch?v=Y4FrUMUItMY&t=174s&ab_channel=D%C6%B0%C6%A1ng%C4%90%E1%BB%8BaL%C3%BD
- List available caption languages:
```python
pytube https://www.youtube.com/watch?v=Y4FrUMUItMY&t=174s&ab_channel=D%C6%B0%C6%A1ng%C4%90%E1%BB%8BaL%C3%BD -lc
```
- Download caption file
```python
pytube https://www.youtube.com/watch?v=Y4FrUMUItMY&t=174s&ab_channel=D%C6%B0%C6%A1ng%C4%90%E1%BB%8BaL%C3%BD -c vi
```

**Comment by RONNCC** [comment]
is this still an issue?

**Comment by Sovenok-Hacker** [comment]
idk

**Pull request closed without merging**
