### PR TITLE
fixes #1098

### LINKED ISSUE #1098: [BUG?][QUESTION] What does this error means?
Hello, after downloading some songs, I got this error raised: `RegexMatchError:  get_throttling_function_name: could not find match for multiple`

What does this mean and how could I fix it/ make an workaround for it?

### LINKED ISSUE #1107: [BUG] pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple
I did this simple code for downloading videos:

`from pytube import YouTube

link = input("Link:  ")
yt = YouTube(link)

print("Title: ",yt.title)
print("Number of views: ",yt.views)
print("Length of video: ",yt.length)
print("Rating of video: ",yt.rating)

ys = yt.streams.get_highest_resolution()

ys.download()`

But every time with every video I get the same error:
image

I have this python version: 
image

And this Pytube version: 
image

### PR DESCRIPTION
**Pull request by vercingetorx**
modify regex for throttle function name id.

### CODE REVIEW

**Comment by glubsy** [comment]
Fixes #1100

**Comment by Chattox** [comment]
Fixes #1098

**Comment by bigbear22941** [comment]
Doesn't work :(

**Comment by ghost** [comment]
> Doesn't work :(

It worked for me.

**Comment by dkradke** [comment]
Works for me :)

**Comment by dzc0d3r** [comment]
fixes [#1098](https://github.com/pytube/pytube/issues/1098) &&  [#1105 ](https://github.com/pytube/pytube/issues/1105) 
Can we get this PR merged?

**Comment by zhar97** [comment]
@Tugamer89 from #1107 not able to fix the issue. @xioren , how did you come up with an alternative regex pattern? Please lead us with a diagnosis over the issue especially for isolated cases.

**Comment by vercingetorx** [comment]
@zhar97 The changes are minor and should work on all videos; I haven't had any issues. Please provide a link to a video where it doesn't work so I can verify.

**Comment by kschubert417** [comment]
This works for me, thanks!

**Comment by tfdahlin** [comment]
@xioren made a couple small changes, will merge once the tests pass

**Comment by tfdahlin** [comment]
Released in v11.0.1 -- update to the latest version with `python3 -m pip install --upgrade pytube`. I included a couple other bugfixes I had been working on as well in this release.

**Comment by RNavega** [comment]
Since the function name is only used to find the function body, you can skip to the body directly by looking for a pattern exclusive to it, then backtracking (`string.rfind`) to something less specific. I'm using this:

```
def get_throttling_function_code(js):
    fiduciary_index = js.find('enhanced_except_')
    if fiduciary_index == -1:
        raise Exception(...)

    start_index = js.rfind('=function(', 0, fiduciary_index)
    start_index = js.rfind(';', 0, start_index)
    if start_index == -1:
        raise Exception(...)
    else:
        # Skip the semicolon, to grab only "xxx=function("
        start_index += 1 

    end_pattern = '};'
    end_index = js.find(end_pattern, fiduciary_index)
    if end_index == -1:
        raise Exception(...)
    else:
        # Skip ahead to include the end pattern in the output.
        end_index += len(end_pattern)

    return js[start_index:end_index].strip()
```
With this you don't need `get_throttling_function_name()` anymore, but it shouldn't make that much difference since this function is only called once per video playback.

**Pull request merged**
