### PR TITLE
fixing : could not find match for multiple

### PR DESCRIPTION
**Pull request by Mjid1**

### CODE REVIEW

**Comment by NullVoidKage** [comment]
Hello when it will merged?
I am having a problem with my website pulling the api

**Comment by Mjid1** [comment]
When the admins approve it, you can try to modify the library file "cipher.py" inside your host

**Review by dionesramos-sv — APPROVED** [review]

**Comment by Nu11Gl1tch** [comment]
Works perfectly

**Comment by NullVoidKage** [comment]
Not merge yet :(

**Comment by NullVoidKage** [comment]
why still not merge

**Pull request closed without merging**
