### PR TITLE
Updated Pipfile.lock to use latest library versions.

### PR DESCRIPTION
**Pull request by tfdahlin**
This should cause most of the dependabot PRs to close automatically, if merged. Running pytest with these dependencies installed seemed to be successful locally.

### CODE REVIEW

**Comment by tfdahlin** [comment]
cc: @RONNCC

**Comment by RONNCC** [comment]
@tfdahlin  should we be concerned by failing checks?

**Comment by tfdahlin** [comment]
@RONNCC yeah, that's a good point, when I pinged you the CI build was still processing I think. I'll look into fixing that. I think we may want to drop the isort extension to flake8 altogether, honestly. There are a few imports that need to happen in a specific order to prevent import loops, and `flake8-isort` only cares about alphabetizing imports. What do you think about removing `flake8-isort` from the test build?

**Comment by RONNCC** [comment]
@tfdahlin  sounds good to me -- as long as flake8 is there i'm not concerned about the rest as much

**Comment by tfdahlin** [comment]
Removed the flake8-isort dependency, CI tests are passing again
cc: @RONNCC

**Comment by RONNCC** [comment]
Thanks @tfdahlin

**Pull request merged**
