### PR TITLE
CLI: Windows Compatability and Enhancements

### PR DESCRIPTION
**Pull request by Medstar117**
Known issues addressed:
#380 (if user was using the CLI)
#362
#202
#180 (sort of)

Updates:
Added compatability for Windows to "get_terminal_size" as to prevent cli.py from crashing when downloading a stream.
**For Linux and OSX users**, the os.popen call for "stty size" has been replaced with a subprocess.check_output call. This tweak prevents stderr from displaying an invalid bash command error on Windows every time the progress bar is updated; because this puts the "display_progress_bar" function into a different process, this edit also has a side effect of reducing download time slightly (bonus!).
If either attempt at getting the terminal geometry fails, the default values are returned as follows in an attempt to prevent an error: rows: 80, columns: 24.

Enhancements:
Added optional arguments for a target directory and a custom name for the downloaded stream.
If either argument isn't specified, the default action occurs for each (target is current working directory and name is the stream's original name, both of which are stream.download's defaults).

### CODE REVIEW

**Comment by Medstar117** [comment]
Oof, that's a lot of coverage loss...any help on fixing that would be greatly appreciated. :)

Also, should I split this PR into two separate ones--one for Windows coverage, and one for the new arguments? Or should I leave it as one bulk PR?

Edit:
Well, that coverage boost attempt helped a bit...it's better than -3.2%. I'm just not experienced enough to work with the mock module to create any meaningful tests for this.

**Comment by stdedos** [comment]
@Medstar117 probably the loss of coverage is because of the new functionality you've added.

Since I don't see CI running a mock test on Windows (and expect any kind of meaninful results), why don't you split the Windows stuff? It will give better visibility

**Comment by Medstar117** [comment]
Oh wow XD Didn't think anyone saw this; been so long since I looked at this that I thought I was shoved to the bottom of the barrel!

Thank you for the reply @stdedos; so you're saying I should split this PR into two separate ones--one for Windows compatibility and one for the enhancements?

**Comment by stdedos** [comment]
Well, I am waiting for my stuff to merge, and a lot of people open a bug report about the same things ... Sometimes I like to chime in 😄 

It is generally a good idea to merge separate "things" separately. It makes it easier for the owner when/if they decide to take a look at it

**Comment by Medstar117** [comment]
Gotcha, I'll get on that as soon as I can. Thanks for the tip!

Also, sorry for the late reply, been away from the PC for a while XD

**Pull request closed without merging**
