### PR TITLE
hotfix parses the throttling array javascript error nontype

### PR DESCRIPTION
**Pull request by thinhpm**
Fix error 'NoneType' object has no attribute 'span'

### CODE REVIEW

**Comment by Derpiesaurus** [comment]
Not sure if people usually are able to publicly show a like for a pull request as I don't use my Github account often, but I don't see a button so I'll comment that this worked perfectly, so thank you!

**Comment by 89z** [comment]
https://github.com/pytube/pytube/issues/1163

**Comment by glubsy** [comment]
Perhaps changing the regex would be beneficial as well, as mentioned [here](https://github.com/pytube/pytube/issues/1163#issuecomment-975428526).

Also adding some tests to the test suite would be a good idea.

**Comment by RONNCC** [comment]
hey @thinhpm  

Thanks for the PR!

If this is still relevant, could you add the following:

- a unit test to show the behavior before and after
- some context on the need for the change

Ideally this would 'break' in the future when youtube also changes behavior again and we can show it as a regression

**Pull request closed without merging**
