### PR TITLE
Add author for youtube video

### PR DESCRIPTION
**Pull request by DmitryBurnaev**
I suggest to add new property for `YouTube` object. It is useful for me.

### CODE REVIEW

**Comment by hbmartin** [comment]
@DmitryBurnaev can you provide tests for this?

**Comment by DmitryBurnaev** [comment]
> @DmitryBurnaev can you provide tests for this?

Did you mean `tests.test_streams.test_author` ? 
That's my test (already in commit)
```
def test_author(cipher_signature):
    expected = 'Test author'
    cipher_signature.player_config_args = {
        'player_response': {'videoDetails': {'author': expected}}
    }
    assert cipher_signature.author == expected

    expected = 'unknown'
    cipher_signature.player_config_args = {}
    assert cipher_signature.author == expected
```

**Comment by hbmartin** [comment]
@DmitryBurnaev derp, added to my pytube3 fork, thanks!

**Comment by RONNCC** [comment]
Issue seems to be fixed already -- please re-open if this isn't the case :)

**Pull request closed without merging**
