### PR TITLE
Fix for RegexMatchError: get_transform_object: could not find match for var for={(.*?)}; bug

### PR DESCRIPTION
**Pull request by untilhamza**
## What is this PR for:
- Handles issue #1728.
- Instead of raising an error, we return an empty list and log the error in the logger using logger.debug.

### CODE REVIEW

**Comment by BuildWithData** [comment]
this is great, thanks for sharing it !!! Question: have you managed to run the test suite ? tried but without success https://youtu.be/N0_ctnsKlmw

**Comment by MarvinSchenkel** [comment]
Thanks for sharing! I just tried it, but using this PR as a dependency now results in the following error:

`pytube.exceptions.RegexMatchError: parse_function: could not find match for js_func_patterns`

Any ideas?

**Comment by BuildWithData** [comment]
hey @MarvinSchenkel I patched pytube with this pull and it works fine for me but I have some changes already in place, you can check all the files I have patched [here](https://github.com/BuildWithData/Code-From-Videos/tree/master/pytube/patch). If you are having troubles patching, I made a [tutorial](https://youtu.be/Or7aNnrLF6s ) on how to do it

**Comment by MarvinSchenkel** [comment]
> 

I use `pytube` as a dependency, so I do not manually patch but just reference this PR as a dependency instead of the `main` branch.

**Comment by BuildWithData** [comment]
ah I see but I guess its not working bcs you need multiple pull requests, anyway patching is really easy, give it a go but if you wanna still go as you do it, [here](https://github.com/BuildWithData/Code-From-Videos/blob/master/pytube/patch/ReadMe.txt) it is the list of pull requests I used so far

**Comment by MarvinSchenkel** [comment]
> ah I see but I guess its not working bcs you need multiple pull requests, anyway patching is really easy, give it a go but if you wanna still go as you do it, [here](https://github.com/BuildWithData/Code-From-Videos/blob/master/pytube/patch/ReadMe.txt) it is the list of pull requests I used so far

That actually makes a lot of sense. Do you happen to have a fork of `pytube` available somewhere with the latest patches applied?

**Review by glubsy — CHANGES_REQUESTED** [review]
This fixes nothing at all, except *trying* to silently ignore the error for potentially more errors to crop up down the line. 

The transform_plan property is still expected to have at least one item in the returned list if there was no error during regex matching (see `Cipher` constructor).

**Pull request closed without merging**
